CROSS   = aarch64-linux-gnu-
CC      = $(CROSS)gcc
LD      = $(CROSS)ld
OBJCOPY = $(CROSS)objcopy

# Source layout (modular):
#   kernel/   - boot, CPU/MMU, mailbox, UART, core kernel
#   drivers/  - SD, FAT, PCIe, xHCI, USB HID, graphics, fonts, logo
#   basic/    - the BASIC interpreter (shared by target and host)
#   seed/     - native "seed" extension API, backends, runtime, examples
#   include/  - shared platform contracts (console.h, storage.h)
#   host/     - host (Linux) backends for the native test build
KERNEL_DIR  = kernel
DRIVERS_DIR = drivers
BASIC_DIR   = basic
SEED_DIR    = seed
INCLUDE_DIR = include
HOST_DIR    = host
BUILD_DIR   = build

# Header search path shared by every target object.
# berry_services.h + seed.h live with the berry-libc in podlib/include. That dir
# is also a freestanding libc (its stdint.h/errno.h/... would shadow the system
# ones), so it goes in via -idirafter: searched only AFTER the system/compiler
# headers, so the ABI headers are found without the libc headers stealing names.
# -I$(BUILD_DIR) is FIRST so the generated headers there are found: conf.h and
# buildconfig.h live ONLY in build/ (no committed copy), so configuring writes
# only into build/ and never dirties the tracked source.
INCLUDES = -I$(BUILD_DIR) -I$(INCLUDE_DIR) -I$(KERNEL_DIR) -I$(DRIVERS_DIR) -I$(BASIC_DIR) -I$(SEED_DIR) \
           -idirafter podlib/include

# -mstrict-align: the MMU is disabled early, so all memory is treated as Device
# memory where unaligned 16/32-bit accesses fault. This stops the compiler
# from synthesising unaligned loads/stores (e.g. merging two byte reads of a
# USB descriptor field into one ldrh), which otherwise crashes enumeration.
# -MMD -MP: emit a .d file per object listing every header (and #included .inc
# fragment) it depends on, so edits to a header or to basic.c's interp_*.inc
# fragments correctly trigger a rebuild. The .d files are pulled in below.
CFLAGS  = -Wall -O2 -ffreestanding -nostdlib -nostartfiles \
          $(INCLUDES) -mcpu=cortex-a72 -mstrict-align -MMD -MP $(CFLAGS_EXTRA)

LDFLAGS = -T $(KERNEL_DIR)/linker.ld

# The glyph table lives ONLY in build/ (no committed copy): it is generated by
# tools/configure.sh - interactively via `make config`, or with defaults by the
# build rule below when build/ has no configuration yet. It is compiled by its own
# rule (further down) to a fixed object.
FONT_DATA = $(BUILD_DIR)/font_data.c

# Target image = kernel + drivers + the interpreter + the seed target backend.
# (drivers/font_data.c no longer exists; the glyph table is $(FONT_DATA) in build/.)
TGT_C = $(wildcard $(KERNEL_DIR)/*.c) $(wildcard $(DRIVERS_DIR)/*.c) \
        $(BASIC_DIR)/basic.c $(wildcard $(BASIC_DIR)/interp_*.c) \
        $(SEED_DIR)/seed_target.c
TGT_S = $(wildcard $(KERNEL_DIR)/*.S)

# Objects are flattened into build/ (every source basename is unique). font_data.o
# is added explicitly since its source ($(FONT_DATA)) is generated into build/.
OBJ = $(addprefix $(BUILD_DIR)/,$(notdir $(TGT_C:.c=.o) $(TGT_S:.S=.o))) $(BUILD_DIR)/font_data.o

# basic.c #includes "conf.h": a generated header carrying the copyright banner
# plus build information (version, date, git revision). tools/genconf.sh writes
# it and only rewrites on a real change, so depending on the phony FORCE keeps
# the stamp fresh without recompiling basic.o on every make. Shared by the host
# and CMake test builds too (see `host` and `test`/`coverage` below). The rule
# itself is defined below `all:` so it does not steal the default goal. It is
# generated INTO the build directory (reached via -I$(BUILD_DIR) above), so a
# configure/build never touches - or dirties - the tracked source tree.
CONF_H = $(BUILD_DIR)/conf.h

# Let pattern rules find each source in its directory.
vpath %.c $(KERNEL_DIR) $(DRIVERS_DIR) $(BASIC_DIR) $(SEED_DIR)
vpath %.S $(KERNEL_DIR)

ELF    = $(BUILD_DIR)/kernel.elf
KERNEL = $(BUILD_DIR)/kernel8.img

all: $(KERNEL)

# Regenerate the build-info header (see CONF_H above). FORCE makes genconf.sh
# run every build; it only rewrites conf.h when the stamp actually changes.
$(CONF_H): FORCE | $(BUILD_DIR)
	@tools/genconf.sh $@
FORCE:
.PHONY: FORCE

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

# The build-dir configuration (buildconfig.h + font_data.c + config.txt). There is
# no committed copy of these; when build/ has none, generate the DEFAULT set via
# the configure script (one run produces all three - a GNU Make grouped target,
# '&:'). `make config` overwrites them interactively; `make clean` drops them so
# the next build regenerates the defaults.
$(BUILD_DIR)/buildconfig.h $(BUILD_DIR)/font_data.c $(BUILD_DIR)/config.txt &: | $(BUILD_DIR)
	@tools/configure.sh --defaults >/dev/null

# Every object needs build/buildconfig.h to exist before the first compile (on a
# clean build there is no auto-dependency .d yet). Order-only so a later change to
# it rebuilds via the .d normal dependency, not on mere newness.
$(OBJ): | $(BUILD_DIR)/buildconfig.h

$(ELF): $(OBJ) | $(BUILD_DIR)
	$(LD) $(LDFLAGS) -o $@ $^

$(KERNEL): $(ELF)
	$(OBJCOPY) $< -O binary $@

$(BUILD_DIR)/%.o: %.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# The glyph table, from build/ (after `make config`) or the committed default.
# An explicit rule (specific target beats the pattern rule) so its source path
# is FONT_DATA, not resolved through vpath.
$(BUILD_DIR)/font_data.o: $(FONT_DATA) | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# The interpreter objects include conf.h (via interp_base.h); make sure the
# generated header exists before the first compile (the auto-dependency .d does
# not exist yet on a clean build).
$(BUILD_DIR)/basic.o: $(CONF_H)
$(patsubst $(BASIC_DIR)/%.c,$(BUILD_DIR)/%.o,$(wildcard $(BASIC_DIR)/interp_*.c)): $(CONF_H)

# Pull in the auto-generated header/fragment dependencies (from -MMD). This is
# what makes a header edit (or a change to one of basic.c's interp_*.inc
# fragments) rebuild every object that includes it.
-include $(OBJ:.o=.d)

$(BUILD_DIR)/%.o: %.S | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# drivers/image.c compiles the vendored stb_image.h, which needs the third_party
# path and the freestanding <stdlib.h>/<string.h> shims. Disable warnings for the
# third-party header (it is not our code).
$(BUILD_DIR)/image.o: CFLAGS += -Ithird_party -Ithird_party/stb_shim -w

# drivers/ttf.c compiles the vendored stb_truetype.h. It defines every STBTT_*
# hook itself (so stb pulls in no system headers), needing only the third_party
# path; -w silences warnings from the third-party header.
$(BUILD_DIR)/ttf.o: CFLAGS += -Ithird_party -w

clean:
	rm -rf $(BUILD_DIR)          # conf.h now lives inside it

# Interactively choose the native resolution, font and keyboard. It writes the
# generated inputs (buildconfig.h, font_data.c, config.txt) into build/ ONLY -
# overriding the committed defaults in the tree without dirtying git - then a
# plain 'make' builds for the new configuration. `make clean` reverts to the
# defaults (re-run `make config` to reconfigure).
config:
	tools/configure.sh

# Scaffold a new native seed in seed/garden/<name>/ (starter source + a Makefile
# that builds the .sed). Prompts for the name, or: make newseed NAME=blur
newseed:
	@tools/newseed.sh $(NAME)

# SD card image for BASIC LOAD/SAVE. Create a blank FAT16 disk with:
#   make sdcard
SDIMG = sd.img

$(SDIMG):
	dd if=/dev/zero of=$@ bs=1M count=64
	mkfs.fat -F 16 -n BERRYDISK $@

sdcard: $(SDIMG)

# Build a bootable Raspberry Pi 4 SD-card image (firmware + kernel + config.txt)
# that runs BerryBasic on real hardware. See tools/mksdimage.sh and README-realhw.md.
# DOOM (third_party/DOOM/linuxdoom-1.10) built to a POD by tools/builddoom.sh and
# shipped to /DOOM on the card (with DOOM1.WAD, if present) by mksdimage.sh.
DOOM_DIR = third_party/DOOM/linuxdoom-1.10
DOOM_POD = $(BUILD_DIR)/sys/DOOM.POD
$(DOOM_POD): $(wildcard $(DOOM_DIR)/*.c) $(wildcard $(DOOM_DIR)/*.h) tools/builddoom.sh \
             $(TCC_SVC_HDR) $(POD_TCC) $(wildcard podlib/src/*) | $(BUILD_DIR)
	tools/builddoom.sh $@
doom: $(DOOM_POD)

sdimage: $(KERNEL) seeds pods doom
	tools/mksdimage.sh

# Interactively flash berrybasic-sd.img to a removable card (lists devices,
# excludes the system disk, confirms before erasing). Avoids flashing the wrong
# disk. Builds the image first if needed.
flash: sdimage
	tools/flashsd.sh

run: $(KERNEL) $(SDIMG)
	qemu-system-aarch64 -M raspi4b -m 2G -kernel $(KERNEL) \
	    -serial stdio -display gtk -device usb-kbd -device usb-mouse \
	    -drive file=berrybasic-sd.img,if=sd,format=raw

# Native build of the interpreter for fast testing/debugging on the host.
# basic/basic.c is shared with the target; only the backends differ.
HOSTCC      = cc
HOST_BIN    = $(BUILD_DIR)/basic_host
HOST_INC    = -I$(INCLUDE_DIR) -I$(BASIC_DIR) -I$(SEED_DIR) -I$(DRIVERS_DIR) -Ithird_party \
              -I$(BUILD_DIR) -idirafter podlib/include
HOST_SRC    = $(BASIC_DIR)/basic.c $(wildcard $(BASIC_DIR)/interp_*.c) \
              $(HOST_DIR)/console_host.c $(HOST_DIR)/storage_host.c \
              $(SEED_DIR)/seed_host.c $(HOST_DIR)/image_host.c $(HOST_DIR)/sound_host.c \
              $(HOST_DIR)/gpio_host.c $(HOST_DIR)/i2c_host.c $(HOST_DIR)/ttf_host.c $(HOST_DIR)/gfx_host.c \
              $(DRIVERS_DIR)/usb_hid.c $(HOST_DIR)/main.c

host: $(CONF_H) $(HOST_SRC) | $(BUILD_DIR)
	$(HOSTCC) -Wall -g $(HOST_INC) -o $(HOST_BIN) $(HOST_SRC) -lm

# Unit tests (Catch2) for the interpreter, configured by basic/CMakeLists.txt.
#   make test        build + run the test suite
#   make coverage    build instrumented, run tests, emit an HTML+text report
TEST_BUILD    = $(BUILD_DIR)/tests
COV_BUILD     = $(BUILD_DIR)/tests-cov

# The '&&' chaining is intentional: it runs the recipe through the shell (whose
# PATH search skips a stray directory named 'cmake') and stops on first failure.
test: $(CONF_H)
	cmake -S basic -B $(TEST_BUILD) -DCMAKE_BUILD_TYPE=Debug && \
	cmake --build $(TEST_BUILD) -j && \
	ctest --test-dir $(TEST_BUILD) --output-on-failure

coverage: $(CONF_H)
	cmake -S basic -B $(COV_BUILD) -DCOVERAGE=ON && \
	cmake --build $(COV_BUILD) --target coverage && \
	echo "HTML report: $(COV_BUILD)/coverage/index.html"

# Native "seeds": position-independent AArch64 blobs that BASIC loads with SEED
# and calls with CALL/CALL$. Built with the same bare-metal toolchain as the
# kernel, linked flat (seed/seed.ld), and gated on being genuinely
# position-independent (see SEED_BAD_RELOC below).
#   make seeds
# -I.../include gives seeds the freestanding seed libc (<stdlib.h>, <string.h>,
# <ctype.h>); -I.../seed finds "seed.h".
# Each seed example is its own project dir: examples/seeds/<name>/<name>.c (+ a
# GROW and a README, so it also builds on the machine with `grow`). The gcc
# cross build here still produces the prebuilt /SEED blobs from the same sources.
SEED_SRC = $(wildcard examples/seeds/*/*.c)
SEED_OUT = $(foreach s,$(SEED_SRC),$(BUILD_DIR)/seeds/$(notdir $(s:.c=.sed)))
SEED_CFLAGS = -O2 -ffreestanding -nostdlib -fno-builtin -mcpu=cortex-a72 -mstrict-align \
              -mcmodel=tiny -fno-pic -ffunction-sections -fdata-sections -DBERRY_SEED \
              -Ipodlib/include -I$(SEED_DIR) -I$(TCC_DIR)/include

# The C library is the ONE berry-libc in podlib/ - the same sources a POD links,
# now also compiled (with the seed toolchain) into each seed; --gc-sections drops
# whatever a given seed doesn't use. crt0/setjmp are POD-only (a seed enters via
# SEED_EXPORT, not main), so they are not in this list.
SEED_RT_SRC = $(addprefix podlib/src/,string.c stdlib.c stdio.c misc.c extra.c graphics.c math.c time.c)
SEED_RT_OBJ = $(patsubst podlib/src/%.c,$(BUILD_DIR)/seeds/rt_%.o,$(SEED_RT_SRC))

# The self-containment gate. A seed is copied to whatever address a slot happens
# to be at, so every address inside it must be computed relative to the program
# counter. Undefined symbols (reaching for libc) already stop the link; what
# this catches is the quieter failure: an address *resolved at link time* and
# baked into the blob as a constant, which ld is perfectly happy to do and which
# would then point at the link-time address (near 0) rather than the load
# address. The classic source is a pointer that must really exist in memory:
#
#     static const char *names[] = { "a", "b" };   // 2x R_AARCH64_ABS64
#
# --emit-relocs keeps the relocation records in the .elf *after* ld resolves
# them, so we can see which kind each address used. PC-relative types
# (ADR_PREL_*, CALL26, JUMP26, LD_PREL_*) are exactly what we want; the absolute
# ones below are the bug. The records are not SHF_ALLOC, so objcopy leaves them
# out and the .sed blob is byte-for-byte what it was without the flag.
SEED_BAD_RELOC = R_AARCH64_(ABS(16|32|64)|MOVW_UABS)

seeds: $(SEED_OUT)

$(BUILD_DIR)/seeds/rt_%.o: podlib/src/%.c | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/seeds
	$(CC) $(SEED_CFLAGS) -c $< -o $@

.SECONDEXPANSION:
$(BUILD_DIR)/seeds/%.sed: examples/seeds/$$*/$$*.c podlib/include/seed.h $(SEED_DIR)/seed.ld $(SEED_RT_OBJ) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/seeds
	$(CC) $(SEED_CFLAGS) -c $< -o $(BUILD_DIR)/seeds/$*.o
	$(LD) --emit-relocs --gc-sections -T $(SEED_DIR)/seed.ld \
	    $(BUILD_DIR)/seeds/$*.o $(SEED_RT_OBJ) -o $(BUILD_DIR)/seeds/$*.elf
	@if $(CROSS)readelf -rW $(BUILD_DIR)/seeds/$*.elf | grep -qE '$(SEED_BAD_RELOC)'; then \
	    echo "SEED ERROR: $< is not position-independent - it has absolute addresses"; \
	    echo "  baked in, which would point at the link-time address once loaded:"; \
	    $(CROSS)readelf -rW $(BUILD_DIR)/seeds/$*.elf | grep -E '$(SEED_BAD_RELOC)'; \
	    rm -f $@; exit 1; fi
	$(OBJCOPY) -O binary $(BUILD_DIR)/seeds/$*.elf $@
	@echo "  built seed $@"

# --- POD executables -------------------------------------------------------
# Whole native programs built with the BerryBasiC tcc (third_party/tinycc). The
# `arm64-tcc -pod` output IS a runnable .POD (flat, checksummed, position-
# independent), so there is no separate link/wrap step. mksdimage.sh drops the
# results onto the data card so RUN "NAME.POD" / PODLOAD find them.
TCC_DIR  = third_party/tinycc
POD_TCC  = $(TCC_DIR)/arm64-tcc
# The unified services table (podlib/include/berry_services.h) is the single
# source of truth for both the seed and POD ABI, and lives with the rest of the
# berry-libc headers. The compiler ships its own include tree, so mirror the
# header there; it is a generated copy (see .gitignore). Every POD rule depends
# on $(POD_TCC), which order-only-depends on this, so it is refreshed first.
TCC_SVC_HDR = $(TCC_DIR)/include/berry_services.h
# seed.h rides along in the compiler include tree too, so `tcc -seed prog.c`
# finds <seed.h> on the machine (it pulls in berry_services.h + stdint.h, which
# already ship to /SYS/INCLUDE). Also a generated copy (see .gitignore).
TCC_SEED_HDR = $(TCC_DIR)/include/seed.h
POD_SRC  = $(wildcard $(TCC_DIR)/examples/pod_*.c)
POD_OUT  = $(patsubst $(TCC_DIR)/examples/pod_%.c,$(BUILD_DIR)/pods/%.POD,$(POD_SRC))
# The applications installed to /sys live under programs/ (see APP_LIST below).
# The `sum` demo command and the MATH.PKT demo packet are example sources under
# examples/pods/ (they ship to /EXAMPLES/PODS too), but are still built and
# installed so `sum` works and on-device PODs can `-l MATH`.
SUM_POD  = $(BUILD_DIR)/sys/SUM.POD
# tcc itself, built as a POD (self-hosting C compiler on the machine).
TCC_POD  = $(BUILD_DIR)/sys/tcc.POD
# Seed packets (.PKT): static libraries in /SYS/LIB. examples/pods/imath.c forms
# MATH.PKT; GFX.PKT is the BGI-style <graphics.h> library over the gfx services.
MATH_SRC    = examples/pods/imath.c
MATH_OBJ    = $(BUILD_DIR)/lib/imath.o
MATH_PKT    = $(BUILD_DIR)/lib/MATH.PKT
GFX_PKT     = $(BUILD_DIR)/lib/GFX.PKT
# CORE.PKT is the pod-libc (stdio/stdlib/string/math128...) as a packet; crt0.o
# is the entry shim, shipped standalone so a main()-based POD can force it in.
# lib-arm64 (128-bit soft-float) is NOT a CORE.PKT member: the on-machine packet
# linker loops on its symbol table. It ships as SOFTFP.O, a plain object grow
# force-links for any pod that uses CORE (printf/double math reach it).
CORE_OBJ    = $(addprefix $(BUILD_DIR)/lib/pl_,stdio.o stdlib.o string.o misc.o extra.o setjmp.o math.o time.o)
CORE_PKT    = $(BUILD_DIR)/lib/CORE.PKT
CRT0_OBJ    = $(BUILD_DIR)/lib/crt0.o
SOFTFP_OBJ  = $(BUILD_DIR)/lib/pl_lib-arm64.o
PODLIB_CC   = $(POD_TCC) -B$(TCC_DIR) -nostdinc -Ipodlib/include -I$(TCC_DIR)/include

# SEEDCORE.PKT: the SAME berry-libc, but compiled with the seed toolchain
# (`tcc -seed -c`, GOT-free PC-relative) so `tcc -seed x.c -l SEEDCORE` links it
# by closure -- the seed analogue of CORE.PKT for pods. A seed pulls only the
# members it references, so a self-contained seed stays tiny. The 128-bit
# soft-float (lib-arm64) packs cleanly as a member here, pulled only by seeds
# that format floating point.
SEEDCORE_CC  = $(POD_TCC) -B$(TCC_DIR) -seed -c -DBERRY_SEED -nostdinc -Ipodlib/include -I$(TCC_DIR)/include
SEEDCORE_OBJ = $(addprefix $(BUILD_DIR)/lib/sc_,string.o stdlib.o stdio.o misc.o extra.o graphics.o setjmp.o lib-arm64.o math.o time.o)
SEEDCORE_PKT = $(BUILD_DIR)/lib/SEEDCORE.PKT

# Native applications: each is a program in programs/<dir>/<dir>.c that installs
# to /SYS as <POD>.POD. An entry is "<dir>:<POD>[:bare]" - the optional ":bare"
# marks a self-contained pod_main POD (built with `tcc -pod`); otherwise it is a
# pod-libc program (linked with the runtime by podcc.sh). To add one, drop
# programs/<name>/<name>.c and add it here. `edit` -> ED.POD (EDIT is a keyword).
APP_LIST = edit:ED grow:GROW show:SHOW echo:ECHO:bare seedrun:SEEDRUN debug:DEBUG
app_dir  = $(word 1,$(subst :, ,$(1)))
app_pod  = $(word 2,$(subst :, ,$(1)))
app_bare = $(word 3,$(subst :, ,$(1)))
APP_OUT  = $(foreach a,$(APP_LIST),$(BUILD_DIR)/sys/$(call app_pod,$(a)).POD)

pods: $(POD_OUT) $(SUM_POD) $(APP_OUT) $(TCC_POD) $(MATH_PKT) $(GFX_PKT) $(CORE_PKT) $(CRT0_OBJ) $(SOFTFP_OBJ) $(SEEDCORE_PKT)

# The `sum` example command (a bare pod_main) installs to /SYS.
$(SUM_POD): examples/pods/sum.c $(TCC_SVC_HDR) $(POD_TCC) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/sys
	$(POD_TCC) -B$(TCC_DIR) -pod $< -o $@
	@echo "  built /sys command $@"

# One rule per application (source programs/<dir>/<dir>.c). Depends on the ABI
# header so an ABI change rebuilds it; pod-libc apps also depend on the runtime.
define APP_RULE
$(BUILD_DIR)/sys/$(call app_pod,$(1)).POD: programs/$(call app_dir,$(1))/$(call app_dir,$(1)).c \
        $(TCC_SVC_HDR) $(POD_TCC) $(if $(call app_bare,$(1)),,tools/podcc.sh $(wildcard podlib/src/*) $(wildcard podlib/include/*)) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/sys
	$(if $(call app_bare,$(1)),$(POD_TCC) -B$(TCC_DIR) -pod $$< -o $$@,tools/podcc.sh $$< $$@)
	@echo "  built /sys program $$@"
endef
$(foreach a,$(APP_LIST),$(eval $(call APP_RULE,$(a))))

$(BUILD_DIR)/lib/pl_%.o: podlib/src/%.c $(TCC_DIR)/include/pod.h $(POD_TCC) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/lib
	$(PODLIB_CC) -c $< -o $@
$(BUILD_DIR)/lib/pl_setjmp.o: podlib/src/setjmp.S $(POD_TCC) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/lib
	$(PODLIB_CC) -c $< -o $@
$(BUILD_DIR)/lib/pl_lib-arm64.o: $(TCC_DIR)/lib/lib-arm64.c $(POD_TCC) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/lib
	$(PODLIB_CC) -c $< -o $@
$(CRT0_OBJ): podlib/src/crt0.c $(TCC_DIR)/include/pod.h $(POD_TCC) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/lib
	$(PODLIB_CC) -c $< -o $@
$(CORE_PKT): $(CORE_OBJ) $(POD_TCC)
	$(POD_TCC) -pkt $@ $(CORE_OBJ)

# SEEDCORE members: the berry-libc under `tcc -seed -c` (PC-relative objects).
$(BUILD_DIR)/lib/sc_%.o: podlib/src/%.c $(TCC_DIR)/include/pod.h $(POD_TCC) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/lib
	$(SEEDCORE_CC) $< -o $@
$(BUILD_DIR)/lib/sc_setjmp.o: podlib/src/setjmp.S $(POD_TCC) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/lib
	$(SEEDCORE_CC) $< -o $@
$(BUILD_DIR)/lib/sc_lib-arm64.o: $(TCC_DIR)/lib/lib-arm64.c $(POD_TCC) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/lib
	$(SEEDCORE_CC) $< -o $@
$(SEEDCORE_PKT): $(SEEDCORE_OBJ) $(POD_TCC)
	$(POD_TCC) -pkt $@ $(SEEDCORE_OBJ)

# MATH.PKT: the imath demo packet (source under examples/pods/). `tcc -pkt`
# derives the symbol table and capabilities from the member.
$(MATH_OBJ): $(MATH_SRC) $(POD_TCC) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/lib
	$(POD_TCC) -B$(TCC_DIR) -c $< -o $@
$(MATH_PKT): $(MATH_OBJ) $(POD_TCC)
	$(POD_TCC) -pkt $@ $(MATH_OBJ)

# The graphics library: one member (graphics.o), compiled against the pod-libc
# headers, packed into GFX.PKT. Its .pod.desc declares CAP_GRAPHICS | CAP_TIME,
# so a POD that links it composes those capabilities automatically.
$(GFX_PKT): podlib/src/graphics.c podlib/include/graphics.h $(TCC_DIR)/include/pod.h $(POD_TCC)
	@mkdir -p $(BUILD_DIR)/lib
	$(POD_TCC) -B$(TCC_DIR) -nostdinc -Ipodlib/include -I$(TCC_DIR)/include -c $< -o $(BUILD_DIR)/lib/graphics.o
	$(POD_TCC) -pkt $@ $(BUILD_DIR)/lib/graphics.o

# The self-hosted compiler: tools/buildtcc.sh compiles tinycc + the pod-libc and
# links them with `arm64-tcc -pod`. Rebuilt when the pod-libc or the wrapper changes.
$(TCC_POD): $(POD_TCC) tools/buildtcc.sh $(TCC_DIR)/tcc_pod.c \
            $(wildcard podlib/src/*) $(wildcard podlib/include/*) $(wildcard podlib/include/sys/*)
	tools/buildtcc.sh $@

# Mirror the single-source services header into the compiler's include tree.
$(TCC_SVC_HDR): podlib/include/berry_services.h
	cp $< $@

$(TCC_SEED_HDR): podlib/include/seed.h
	cp $< $@

# Build the AArch64 cross tcc once (it is what emits target PODs on this host).
$(POD_TCC): | $(TCC_SVC_HDR) $(TCC_SEED_HDR)
	@cd $(TCC_DIR) && [ -f config.mak ] || ./configure >/dev/null
	@$(MAKE) --no-print-directory -C $(TCC_DIR) arm64-tcc

$(BUILD_DIR)/pods/%.POD: $(TCC_DIR)/examples/pod_%.c $(TCC_DIR)/include/pod.h $(POD_TCC) | $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/pods
	$(POD_TCC) -B$(TCC_DIR) -pod $< -o $@
	@echo "  built pod $@"

.PHONY: all clean config newseed sdcard sdimage flash run host seeds pods doom test coverage
