#ifndef BUILDCONFIG_H
#define BUILDCONFIG_H

// ---------------------------------------------------------------------------
// Build-time configuration: screen resolution, font and keyboard layout.
// GENERATED by tools/configure.sh - re-run that script to change it.
// ---------------------------------------------------------------------------

// Native framebuffer resolution (pixels). boot/config.txt drives HDMI to match.
#define CFG_FB_WIDTH   1280
#define CFG_FB_HEIGHT  720

// Glyph cell (source pixels) and draw magnification. The font is 850_LAT1.F18.
#define CFG_GLYPH_W    8
#define CFG_GLYPH_H    18
#define CFG_FONT_SCALE 1

// Default keyboard layout at power-on (two-letter code: US UK NO DK SE DE).
// A program can switch at any time with the KEYBOARD statement.
#define CFG_KBD_LAYOUT "NO"

#endif
