#include <stdint.h>
#include "uart.h"
#include "mailbox.h"
#include "graphics.h"
#include "font.h"
#include "usb_kbd.h"
#include "usb_hid.h"
#include "console.h"
#include "ttf.h"
#include "gfx.h"
#include "basic.h"
#include "mmu.h"
#include "sd.h"
#include "storage.h"
#include "pcie.h"
#include "xhci.h"

// ---------------------------------------------------------------------------
// Display configuration. The native resolution comes from kernel/buildconfig.h
// (generated by tools/configure.sh); a -DFB_WIDTH/-DFB_HEIGHT on the compiler
// command line still overrides it for one-off builds.
// ---------------------------------------------------------------------------
#include "buildconfig.h"
#ifndef FB_WIDTH
#define FB_WIDTH  CFG_FB_WIDTH
#endif
#ifndef FB_HEIGHT
#define FB_HEIGHT CFG_FB_HEIGHT
#endif

// CHAR_W / CHAR_H come from font.h (BBC 8x8 glyph scaled by FONT_SCALE).
// FB_WIDTH/FB_HEIGHT are only the *startup* resolution now; the live resolution
// is g_fb_w/g_fb_h and the text grid g_term_cols/g_term_rows (see below), which a
// program can change with SCREEN and which reset to startup when it finishes.

// Free-running 1 MHz system timer (low 32 bits); used to pace the cursor blink.
#define TIMER_CLO       (*(volatile uint32_t *)(0xFE003004UL))
#define CURSOR_BLINK_US 500000u   // half-period: on 500 ms, off 500 ms

static int cursor_col     = 0;
static int cursor_row     = 0;
static int fb_ready       = 0;
static uint32_t g_fb_phys = 0;   // framebuffer physical base (for non-cacheable remap)
static uint32_t g_fb_size = 0;   // framebuffer size in bytes

// Live display resolution (physical pixels) and the derived text grid. These
// start at the compile-time defaults and are updated whenever the framebuffer is
// reconfigured (SCREEN). g_start_* remembers the boot resolution to restore to.
static uint32_t g_fb_w    = FB_WIDTH;
static uint32_t g_fb_h    = FB_HEIGHT;
static uint32_t g_start_w = FB_WIDTH;
static uint32_t g_start_h = FB_HEIGHT;
// Graphics render target (SPRITETARGET). g_tgt_* are the target's pixel size
// (0 = the screen framebuffer); g_gl_* are the logical coordinate extent - the
// BBC 1280x1024 space for the screen, but the sprite's own pixels (1:1, origin
// bottom-left) when drawing into a sprite.
static int g_tgt_w = 0, g_tgt_h = 0;
static int g_gl_w  = 1280, g_gl_h = 1024;
static int g_term_cols    = FB_WIDTH  / CHAR_W;
static int g_term_rows    = FB_HEIGHT / CHAR_H;
static int cursor_visible = 0;   // whether the cursor glyph is currently drawn
static int cursor_insert  = 1;   // line editor: 1 = insert (bar caret), 0 = overwrite (block)
static uint32_t text_color = COLOR_WHITE;   // current foreground (BBC COLOUR)
static uint32_t text_bg    = COLOR_BLACK;   // current text background (VDU 17,128+c)

// VDU driver state.
static int vdu_enabled    = 1;   // VDU 6 / VDU 21: is screen output enabled?
static int vdu5_mode      = 0;   // VDU 5: write text at the graphics cursor
static int cursor_enabled = 1;   // VDU 23,1: is the text cursor (caret) shown?
// Text viewport, in character cells (inclusive). Default = whole screen.
static int tv_l = 0, tv_t = 0, tv_r = FB_WIDTH / CHAR_W - 1, tv_b = FB_HEIGHT / CHAR_H - 1;

// VDU 5 (text at the graphics cursor) helpers, defined with the graphics code
// further down but used by term_putchar above it.
static void gfx_text_char(unsigned char uc);   // draw a glyph at the gfx cursor, advance
static void gfx_text_cr(void);                 // carriage return (to viewport left)
static void gfx_text_lf(void);                 // line feed (down one char)
static void gfx_text_bs(void);                 // backspace (left one char)

// BBC logical colours 0..7 -> framebuffer RGBA (low byte = R, so 0xAABBGGRR).
// Mutable so VDU 19 can remap the palette; bbc_default_palette is the reset value
// for VDU 20 / MODE.
static const uint32_t bbc_default_palette[8] = {
    0xFF000000,  // 0 black
    0xFF0000FF,  // 1 red
    0xFF00FF00,  // 2 green
    0xFF00FFFF,  // 3 yellow
    0xFFFF0000,  // 4 blue
    0xFFFF00FF,  // 5 magenta
    0xFFFFFF00,  // 6 cyan
    0xFFFFFFFF,  // 7 white
};
static uint32_t bbc_palette[8] = {
    0xFF000000, 0xFF0000FF, 0xFF00FF00, 0xFF00FFFF,
    0xFFFF0000, 0xFFFF00FF, 0xFFFFFF00, 0xFFFFFFFF,
};
// Pack r,g,b (0..255) into a framebuffer pixel (RGB pixel order, red low byte).
static uint32_t rgb_pixel(int r, int g, int b) {
    return 0xFF000000u | ((uint32_t)(b & 0xff) << 16) |
           ((uint32_t)(g & 0xff) << 8) | (uint32_t)(r & 0xff);
}

// ---------------------------------------------------------------------------
// Terminal
// ---------------------------------------------------------------------------

// Flashing text caret at the current cell. Its shape follows the line editor's
// mode (see cursor_insert): overwrite mode shows a 50% checkerboard block, while
// insert mode shows a thin vertical bar down the left edge of the cell. Either
// way the caret never hides the character — the checkerboard leaves half the
// cell's pixels untouched so the glyph shows through the "holes", and the bar
// only touches the leftmost columns. The cell is saved before the pattern is
// laid down, so lifting the caret restores exactly what was there — glyph or
// background — with no redraw.
//   show=1 overlays the pattern, show=0 restores. The visible==show guard is
// essential: the save buffer holds one cell only, so we must never overlay
// twice, and term_advance() clears cursor_visible by hand after a scroll has
// already carried the drawn caret away (its save buffer is then simply stale
// and correctly ignored, because the next show re-saves first).
#define CARET_BAR_W 2                           // insert-mode bar width, in pixels
static uint32_t caret_under[CHAR_W * CHAR_H];   // pixels hidden by the caret

static void cursor_set(int show) {
    if (!fb_ready) return;
    if (show && !cursor_enabled) return;   // VDU 23,1,0 disables the caret
    show = show ? 1 : 0;
    if (show == cursor_visible) return;    // already in that state
    int px = cursor_col * CHAR_W;
    int py = cursor_row * CHAR_H;
    for (int y = 0; y < CHAR_H; y++)
        for (int x = 0; x < CHAR_W; x++) {
            int i = y * CHAR_W + x;
            if (show) {
                caret_under[i] = getpixel(px + x, py + y);
                int lit = cursor_insert ? (x < CARET_BAR_W)   // insert: left-edge bar
                                        : (((x ^ y) & 1) == 0); // overwrite: checkerboard
                if (lit) putpixel(px + x, py + y, COLOR_WHITE);
            } else {
                putpixel(px + x, py + y, caret_under[i]);
            }
        }
    cursor_visible = show;
}

// Newline: carriage-return to the viewport left, move down one row, scrolling the
// text viewport (which is the whole screen by default) when past the bottom.
static void term_advance(void) {
    cursor_col = tv_l;
    if (++cursor_row > tv_b) {
        scroll_rect(tv_l * CHAR_W, tv_t * CHAR_H,
                    (tv_r + 1) * CHAR_W - 1, (tv_b + 1) * CHAR_H - 1,
                    CHAR_H, text_bg);          // scroll one text row up
        cursor_row     = tv_b;                 // stay on the (new) bottom row
        cursor_visible = 0;                    // the scroll wiped any drawn cursor
    }
}

// Draw glyph `uc` (any code 0..255, so user-defined and VDU-27 chars work) at the
// cursor in the current colours, then advance. Caller must have lifted the cursor.
static void term_glyph(unsigned char uc) {
    int px = cursor_col * CHAR_W, py = cursor_row * CHAR_H;
    bar(px, py, px + CHAR_W - 1, py + CHAR_H - 1, text_bg);
    draw_char((char)uc, px, py, text_color);
    if (++cursor_col > tv_r) term_advance();
}

void term_putchar(char c) {
    if (!fb_ready) return;
    if (cursor_visible) cursor_set(0);   // lift cursor before editing the cell
    // VDU 5 mode: all character output (PRINT included) goes to the graphics
    // cursor instead of the text cursor.
    if (vdu5_mode) {
        if (c == '\r') { gfx_text_cr(); return; }
        if (c == '\n') { gfx_text_cr(); gfx_text_lf(); return; }   // PRINT newline = CR+LF
        if (c == '\b') { gfx_text_bs(); return; }
        if ((unsigned char)c < 32) return;
        gfx_text_char((unsigned char)c);
        return;
    }
    if (c == '\r') { cursor_col = tv_l; return; }
    if (c == '\n') { term_advance(); return; }
    if (c == '\t') {
        cursor_col = (cursor_col + 4) & ~3;
        if (cursor_col > tv_r) term_advance();
        return;
    }
    if (c == '\b') {
        if (cursor_col > tv_l) --cursor_col;
        else if (cursor_row > tv_t) { --cursor_row; cursor_col = tv_r; }
        else return;
        bar(cursor_col * CHAR_W, cursor_row * CHAR_H,
            cursor_col * CHAR_W + CHAR_W - 1, cursor_row * CHAR_H + CHAR_H - 1,
            text_bg);
        return;
    }
    if ((unsigned char)c < 32) return;   // other control codes: not printable here
    term_glyph((unsigned char)c);
}

static void term_puts(const char *s) {
    while (*s) term_putchar(*s++);
}

// ---------------------------------------------------------------------------
// Line editor
// ---------------------------------------------------------------------------

static int g_kbd_ok  = 0;   // DWC2 (USB-C) keyboard present
static int g_xhci_ok = 0;   // xHCI/VL805 (USB-A) keyboard present
static int g_sd_ready = 0;  // SD filesystem mounted (boot log can be written)

// Real Pi hardware vs QEMU (nonzero board serial). Read once at boot. The PWM
// audio driver (drivers/sound.c) gates its register access on this, because
// QEMU's raspi4b does not model the PWM peripheral and faults on access.
int g_real_hw = 0;

// Mouse pointer state, in raw framebuffer pixels (origin top-left). Deltas from
// the HID mouse accumulate here; con_mouse() polls and reports it. g_mouse_dwc2
// / g_mouse_xhci record which backend enumerated a mouse.
static int g_mouse_dwc2 = 0;
static int g_mouse_xhci = 0;
static int g_mouse_x = FB_WIDTH / 2;
static int g_mouse_y = FB_HEIGHT / 2;
static int g_mouse_b = 0;

// Software mouse pointer (an arrow sprite drawn on the framebuffer). Defined
// after the mouse poll helpers; forward-declared here because the input-wait
// loops (which run earlier in the file) drive it.
static int  mouse_enabled(void);
static void pointer_tick(void);   // service mouse + repaint the pointer sprite
static void pointer_hide(void);   // remove the sprite (call before any FB write)

// Dump the in-RAM UART log to BOOTLOG.TXT on the SD card. Called at the end of
// boot (to diagnose USB enumeration) and from the exception handler (to surface
// a crash) on a board with no serial cable. Best-effort: needs the filesystem
// mounted, and guards against re-entry (e.g. an exception while already writing).
static void flush_boot_log(void) {
    static int busy = 0;
    if (!g_sd_ready || busy) return;
    busy = 1;
    const char *buf; int len;
    uart_log_get(&buf, &len);
    stg_write("BOOTLOG.TXT", buf, len);
    busy = 0;
}

// Emit a boot-progress line to *both* the UART/RAM log and, once it exists, the
// HDMI framebuffer. On a cableless board the screen is the only channel we know
// works (the firmware drew its own diagnostics on it), so mirroring boot stages
// there means the last line visible on screen is exactly where the kernel hung.
static void boot_msg(const char *s) {
    uart_puts(s);
    if (fb_ready) term_puts(s);
}

static int read_esc_seq(void);   // serial escape-sequence decode (defined below)

// Return the next key from any keyboard (DWC2 USB-C or xHCI USB-A), falling back
// to the UART, or 0 if nothing is pending. A key is an int: printable keys are
// their Latin-1 character, the rest are the KEY_* codes in usb_hid.h.
//
// The USB decode already yields KEY_* codes. A serial terminal instead sends the
// arrows and friends as escape sequences (ESC [ A ...), so those are decoded
// here rather than in one caller - that way a serial arrow key and a USB arrow
// key are the same key to everything above, GET and the line editor alike.
static int term_pollchar(void) {
    int c = 0;
    if (g_kbd_ok)        c = usb_kbd_getchar();
    if (!c && g_xhci_ok) c = xhci_kbd_getchar();
    if (c) return c;                              // already a decoded key

    c = (unsigned char)uart_getc();
    if (c == 0x1B) c = read_esc_seq();            // serial: ESC [ A -> KEY_UP, ...
    return c;
}

// --- command-line history ---------------------------------------------------
#define HIST_MAX 16
#define HIST_LEN 256
static char hist_buf[HIST_MAX][HIST_LEN];
static int  hist_n = 0;      // entries stored (<= HIST_MAX)
static int  hist_head = 0;   // next slot to overwrite

static int kstrlen(const char *s) { int n = 0; while (s[n]) n++; return n; }
static void kstrcpy(char *d, const char *s, int max) {
    int i = 0; while (s[i] && i < max - 1) { d[i] = s[i]; i++; } d[i] = 0;
}
static int kstreq(const char *a, const char *b) {
    while (*a && *b) { if (*a != *b) return 0; a++; b++; } return *a == *b;
}
static void hist_push(const char *s) {
    if (!s[0]) return;
    if (hist_n && kstreq(hist_buf[(hist_head - 1 + HIST_MAX) % HIST_MAX], s)) return;
    kstrcpy(hist_buf[hist_head], s, HIST_LEN);
    hist_head = (hist_head + 1) % HIST_MAX;
    if (hist_n < HIST_MAX) hist_n++;
}
static const char *hist_get(int age) {           // age 1 = most recent
    if (age < 1 || age > hist_n) return 0;
    return hist_buf[(hist_head - age + HIST_MAX) % HIST_MAX];
}

// Poll for one input byte for up to `ms` milliseconds (used to read the rest of
// a terminal escape sequence). 0 = nothing arrived.
static char poll_byte_ms(int ms) {
    uint32_t t0 = TIMER_CLO;
    for (;;) {
        int c = term_pollchar();
        if (c) return c;
        if (TIMER_CLO - t0 >= (uint32_t)ms * 1000) return 0;
    }
}

// Map a terminal CSI escape sequence (after ESC) to an editing key, for serial
// use. The HID keyboard delivers KEY_* codes directly.
static int read_esc_seq(void) {
    if (poll_byte_ms(20) != '[') return KEY_ESC;      // nothing followed: a bare Esc
    char b = poll_byte_ms(20);
    switch (b) {
        case 'A': return KEY_UP;
        case 'B': return KEY_DOWN;
        case 'C': return KEY_RIGHT;
        case 'D': return KEY_LEFT;
        case 'H': return KEY_HOME;
        case 'F': return KEY_END;
        case '2': poll_byte_ms(20); return KEY_INS;   // ESC [ 2 ~
        case '3': poll_byte_ms(20); return KEY_DEL;   // ESC [ 3 ~
        case '5': poll_byte_ms(20); return KEY_PGUP;  // ESC [ 5 ~
        case '6': poll_byte_ms(20); return KEY_PGDN;  // ESC [ 6 ~
        default:  return 0;
    }
}

// Position the framebuffer cursor at editable offset `off` from start (sc,sr).
static void edit_cursor_at(int sc, int sr, int off) {
    int t = sc + off;
    cursor_col = t % g_term_cols;
    cursor_row = sr + t / g_term_cols;
    if (cursor_row >= g_term_rows) cursor_row = g_term_rows - 1;
}

// Redraw the editable region (screen + serial) and place the cursor at `pos`.
static void edit_render(int sc, int sr, const char *prompt,
                        const char *buf, int len, int pos, int prev_len) {
    if (fb_ready) {
        if (cursor_visible) cursor_set(0);
        cursor_col = sc; cursor_row = sr;
        for (int i = 0; i < len; i++) term_putchar(buf[i]);
        for (int i = len; i < prev_len; i++) term_putchar(' ');   // erase leftovers
        edit_cursor_at(sc, sr, pos);
    }
    uart_putc('\r'); uart_puts(prompt);
    for (int i = 0; i < len; i++) uart_putc(buf[i]);
    uart_puts("\033[K");                              // clear to end of line
    for (int i = pos; i < len; i++) uart_putc('\b');  // back to the cursor column
}

// Full line editor: prints `prompt`, starts with `prefill_len` editable chars in
// buf, supports cursor movement (Left/Right/Home/End), backspace/delete, Up/Down
// command history, and an Insert key that toggles insert vs. overwrite editing
// (the caret shows a bar in insert mode, a block in overwrite). Returns the
// final length.
int term_getline_ed(char *buf, int maxlen, int prefill_len, const char *prompt) {
    int len = prefill_len;
    if (len > maxlen - 1) len = maxlen - 1;
    buf[len] = 0;
    int pos = len;

    if (fb_ready) { if (cursor_visible) cursor_set(0); for (const char *p = prompt; *p; p++) term_putchar(*p); }
    int sc = cursor_col, sr = cursor_row;
    int prev_len = 0;
    edit_render(sc, sr, prompt, buf, len, pos, prev_len);
    prev_len = len;

    int hist_age = 0;                 // 0 = editing current; >0 = browsing history
    char saved[HIST_LEN]; saved[0] = 0;
    uint32_t last_blink = TIMER_CLO;

    for (;;) {
        int c = term_pollchar();
        if (!c) {
            uint32_t now = TIMER_CLO;
            if (now - last_blink >= CURSOR_BLINK_US) {
                last_blink = now;
                pointer_hide();                  // hide before drawing the blink cursor
                edit_cursor_at(sc, sr, pos);
                cursor_set(!cursor_visible);
            }
            pointer_tick();                      // move/repaint the pointer on top
            sound_pump();                        // keep queued notes playing while idle
            continue;
        }
        pointer_hide();                          // a key arrived; hide before redrawing

        if (c == '\r' || c == '\n') {
            if (fb_ready) { if (cursor_visible) cursor_set(0); edit_cursor_at(sc, sr, len); term_putchar('\n'); }
            uart_puts("\r\n");
            buf[len] = 0;
            hist_push(buf);
            return len;
        }
        if (c == '\b') {                          // backspace (delete left of cursor)
            if (pos > 0) {
                for (int i = pos - 1; i < len - 1; i++) buf[i] = buf[i + 1];
                len--; pos--; buf[len] = 0;
            }
        } else if (c == KEY_DEL) {                // forward delete
            if (pos < len) {
                for (int i = pos; i < len - 1; i++) buf[i] = buf[i + 1];
                len--; buf[len] = 0;
            }
        } else if (c == KEY_LEFT)  { if (pos > 0)   pos--; }
        else if (c == KEY_RIGHT) { if (pos < len) pos++; }
        else if (c == KEY_HOME)  { pos = 0; }
        else if (c == KEY_END)   { pos = len; }
        else if (c == KEY_UP) {
            if (hist_age < hist_n) {
                if (hist_age == 0) kstrcpy(saved, buf, HIST_LEN);
                kstrcpy(buf, hist_get(++hist_age), maxlen);
                len = kstrlen(buf); pos = len;
            }
        } else if (c == KEY_DOWN) {
            if (hist_age > 0) {
                hist_age--;
                kstrcpy(buf, hist_age == 0 ? saved : hist_get(hist_age), maxlen);
                len = kstrlen(buf); pos = len;
            }
        } else if (c == KEY_INS) {               // toggle insert / overwrite
            cursor_insert = !cursor_insert;
            if (fb_ready) {                       // redraw the caret in its new shape now
                if (cursor_visible) cursor_set(0);
                edit_cursor_at(sc, sr, pos);
                cursor_set(1);
            }
            last_blink = TIMER_CLO;
            continue;                             // buffer unchanged; skip the redraw
        } else if ((c >= 32 && c <= 126) ||
                   (c >= 0xA0 && c <= 0xFF)) {    // printable ASCII or Latin-1 (æ ø å …)
            if (!cursor_insert && pos < len) {
                buf[pos++] = (char)c;             // overwrite the character under the caret
            } else if (len < maxlen - 1) {        // insert (or append at end of line)
                for (int i = len; i > pos; i--) buf[i] = buf[i - 1];
                buf[pos++] = (char)c; len++; buf[len] = 0;
            }
        } else {
            continue;                              // ignore other control codes
        }

        edit_render(sc, sr, prompt, buf, len, pos, prev_len);
        prev_len = len;
        last_blink = TIMER_CLO;
    }
}

int term_getline(char *buf, int maxlen) {
    return term_getline_ed(buf, maxlen, 0, "");
}

// ---------------------------------------------------------------------------
// Console backend for the BASIC interpreter (console.h). Output is mirrored to
// both the framebuffer terminal and the UART so headless/serial use works too.
// ---------------------------------------------------------------------------

void con_putc(char c) {
    if (c == '\n') { term_putchar('\n'); uart_puts("\r\n"); }
    else           { term_putchar(c);    uart_putc(c); }
}

void con_puts(const char *s) {
    while (*s) con_putc(*s++);
}

int con_getline(char *buf, int maxlen) {
    return term_getline(buf, maxlen);   // never EOFs on the target
}

int con_getline_ed(char *buf, int maxlen, int prefill_len, const char *prompt) {
    return term_getline_ed(buf, maxlen, prefill_len, prompt);
}

void con_cls(void) {
    if (fb_ready) {
        if (cursor_visible) cursor_set(0);
        // Clear the text viewport (the whole screen by default) to the text
        // background colour.
        fill_rect(tv_l * CHAR_W, tv_t * CHAR_H,
                  (tv_r + 1) * CHAR_W - 1, (tv_b + 1) * CHAR_H - 1, text_bg);
    }
    cursor_col = tv_l;
    cursor_row = tv_t;
    cursor_visible = 0;
    uart_puts("\r\n");
}

void con_colour(int c) {
    if (c >= 128) text_bg    = bbc_palette[(c - 128) & 7];   // COLOUR 128+c: background
    else          text_color = bbc_palette[c & 7];           // COLOUR c: foreground
}

// Keyboard layout: forward to the shared HID decoder (see drivers/usb_hid.c).
int         con_set_keyboard(const char *code) { return hid_set_layout(code); }
const char *con_get_keyboard(void)             { return hid_layout_code(); }

// Block until a key is pressed; return its ASCII code (BBC GET).
int con_getkey(void) {
    uint32_t last_blink = TIMER_CLO;
    for (;;) {
        int c = term_pollchar();
        if (c) { pointer_hide(); if (cursor_visible) cursor_set(0); return c; }
        uint32_t now = TIMER_CLO;
        if (now - last_blink >= CURSOR_BLINK_US) {
            last_blink = now;
            pointer_hide();                 // hide before drawing the blink cursor
            cursor_set(!cursor_visible);
        }
        pointer_tick();                     // move/repaint the pointer on top
        sound_pump();                       // keep queued notes playing while idle
    }
}

#define TIMER_CHI (*(volatile uint32_t *)(0xFE003008UL))

unsigned long long con_micros(void) {
    uint32_t hi, lo;
    do { hi = TIMER_CHI; lo = TIMER_CLO; } while (hi != TIMER_CHI);  // guard wrap
    return ((unsigned long long)hi << 32) | lo;
}

// Wait up to `centiseconds` (1/100 s) for a key; return its code or -1.
int con_inkey(int centiseconds) {
    uint32_t t0 = TIMER_CLO;
    uint32_t limit = (centiseconds > 0) ? (uint32_t)centiseconds * 10000u : 0;
    uint32_t last_blink = TIMER_CLO;
    for (;;) {
        int c = term_pollchar();
        if (c) { pointer_hide(); if (cursor_visible) cursor_set(0); return c; }
        if (TIMER_CLO - t0 >= limit) { pointer_hide(); return -1; }
        uint32_t now = TIMER_CLO;
        if (now - last_blink >= CURSOR_BLINK_US) {
            last_blink = now;
            pointer_hide();                 // hide before drawing the blink cursor
            cursor_set(!cursor_visible);
        }
        pointer_tick();                     // move/repaint the pointer on top
        sound_pump();                       // keep queued notes playing while idle
    }
}

int con_pos(void)  { return cursor_col; }
int con_vpos(void) { return cursor_row; }
int con_rows(void) { return g_term_rows; }

// Poll whichever USB backend enumerated a mouse and fold the relative movement
// into the absolute pointer position. Raw framebuffer pixels, origin top-left:
// +dX moves right, +dY moves down. Buttons are latched from the last report.
static void mouse_service(void) {
    int btn = 0, dx = 0, dy = 0, wheel = 0, got = 0;
    if (g_mouse_dwc2) got = usb_mouse_poll(&btn, &dx, &dy, &wheel);
    if (!got && g_mouse_xhci) got = xhci_mouse_poll(&btn, &dx, &dy, &wheel);
    if (!got) return;

    g_mouse_b = btn;
    g_mouse_x += dx;
    g_mouse_y += dy;
    if (g_mouse_x < 0) g_mouse_x = 0;
    if (g_mouse_y < 0) g_mouse_y = 0;
    if (g_mouse_x > (int)g_fb_w - 1) g_mouse_x = (int)g_fb_w - 1;
    if (g_mouse_y > (int)g_fb_h - 1) g_mouse_y = (int)g_fb_h - 1;
}

// The modifier/lock snapshot from the shared HID decoder. Both USB backends feed
// the same decoder, so this is right whichever one enumerated; with no USB
// keyboard at all there are no modifiers to report (a serial terminal sends
// characters, not key state).
int con_keymods(void) {
    if (!g_kbd_ok && !g_xhci_ok) return 0;
    return hid_modifiers();
}

void con_mouse(int *x, int *y, int *buttons) {
    mouse_service();
    if (x)       *x = g_mouse_x;
    if (y)       *y = g_mouse_y;
    if (buttons) *buttons = g_mouse_b;
}

// --- software mouse pointer -------------------------------------------------
// A small arrow sprite drawn directly on the framebuffer. It is shown only while
// the console is waiting for input (REPL editor, GET/INKEY), and hidden before
// any character is echoed, so it never corrupts text: the pixels underneath are
// saved on show and restored on hide (save-under). The arrow's tip is the hot
// spot at the top-left, so the sprite's origin is the mouse coordinate.
#define PTR_W 12
#define PTR_H 17
// 'K' = black outline, 'W' = white fill, '.' = transparent (see-through).
static const char ptr_sprite[PTR_H][PTR_W + 1] = {
    "K...........",
    "KK..........",
    "KWK.........",
    "KWWK........",
    "KWWWK.......",
    "KWWWWK......",
    "KWWWWWK.....",
    "KWWWWWWK....",
    "KWWWWWWWK...",
    "KWWWWWWWWK..",
    "KWWWWWKKKKK.",
    "KWWKWWK.....",
    "KWK.KWWK....",
    "KK..KWWK....",
    "K....KWWK...",
    ".....KWWK...",
    "......KK....",
};

static int      g_ptr_shown = 0;
static int      g_ptr_x = 0, g_ptr_y = 0;
static uint32_t g_ptr_save[PTR_W * PTR_H];   // framebuffer pixels under the sprite

static int mouse_enabled(void) { return (g_mouse_dwc2 || g_mouse_xhci) && fb_ready; }

// Restore the pixels the sprite is covering. Must be called before ANY other
// write to the region the pointer occupies (blink cursor, character echo, etc.).
static void pointer_hide(void) {
    if (!g_ptr_shown) return;
    for (int r = 0; r < PTR_H; r++)
        for (int c = 0; c < PTR_W; c++)
            putpixel(g_ptr_x + c, g_ptr_y + r, g_ptr_save[r * PTR_W + c]);
    g_ptr_shown = 0;
}

// Save the background at the current mouse position, then draw the arrow on top.
static void pointer_show(void) {
    if (g_ptr_shown) return;
    g_ptr_x = g_mouse_x;
    g_ptr_y = g_mouse_y;
    for (int r = 0; r < PTR_H; r++)                       // save first (whole box)
        for (int c = 0; c < PTR_W; c++)
            g_ptr_save[r * PTR_W + c] = getpixel(g_ptr_x + c, g_ptr_y + r);
    for (int r = 0; r < PTR_H; r++)                       // then draw opaque cells
        for (int c = 0; c < PTR_W; c++) {
            char p = ptr_sprite[r][c];
            if (p == 'K')      putpixel(g_ptr_x + c, g_ptr_y + r, COLOR_BLACK);
            else if (p == 'W') putpixel(g_ptr_x + c, g_ptr_y + r, COLOR_WHITE);
        }
    g_ptr_shown = 1;
}

// Called from input-wait loops: poll the mouse and, if the pointer moved (or is
// not currently drawn), repaint it. A no-op when the pointer is already up to
// date, so it is cheap to call at the polling rate.
static void pointer_tick(void) {
    if (!mouse_enabled()) return;
    if (gfx_buffered() || g_tgt_w > 0) return;   // never draw the arrow off-screen
    mouse_service();
    if (g_ptr_shown && g_ptr_x == g_mouse_x && g_ptr_y == g_mouse_y) return;
    pointer_hide();
    pointer_show();
}

// ---------------------------------------------------------------------------
// Boot logo (embedded RGB image from logo_data.c)
// ---------------------------------------------------------------------------

extern const unsigned int  logo_w;
extern const unsigned int  logo_h;
extern const unsigned char logo_rgb[];

static int g_show_logo = 0;   // set at boot once the framebuffer is up

// Draw the embedded RGB logo at framebuffer pixel (ox, oy), shrunk by integer
// factor `div` (nearest-neighbour). Colours are already baked into logo_rgb
// (black background, green leaves, raspberry-red berry). The framebuffer is
// RGBA byte-order (low byte = R), so a pixel is 0xFF000000 | B<<16 | G<<8 | R.
static void draw_logo(int ox, int oy, int div) {
    unsigned int dw = logo_w / div, dh = logo_h / div;
    for (unsigned int y = 0; y < dh; y++) {
        for (unsigned int x = 0; x < dw; x++) {
            const unsigned char *p = logo_rgb + ((y * div) * logo_w + (x * div)) * 3;
            uint32_t r = p[0], g = p[1], b = p[2];
            putpixel(ox + (int)x, oy + (int)y,
                     0xFF000000u | (b << 16) | (g << 8) | r);
        }
    }
}

// Show the boot splash. On the target this clears the boot-progress text, paints
// the logo on the left, prints the banner beside it (vertically centred on the
// logo), parks the text cursor cleanly below the logo, and returns 1 so the
// caller does not print the banner again. Returns 0 when no logo is shown (e.g.
// the host build), in which case the caller prints the banner itself.
int con_splash(const char *banner) {
    if (!g_show_logo || !fb_ready) return 0;
    cleardevice();                                    // wipe the boot-progress text
    int div = 2;                                      // half size
    int lw = (int)logo_w / div, lh = (int)logo_h / div;
    int ox = CHAR_W;                                  // small left margin
    int oy = CHAR_H;                                  // small top margin
    draw_logo(ox, oy, div);                           // left side, half size

    // Banner beside the logo, vertically centred on it.
    cursor_col = (ox + lw) / CHAR_W + 1;
    cursor_row = (oy + lh / 2) / CHAR_H;
    cursor_visible = 0;
    con_puts(banner);
    uart_puts("\r\n");                                // tidy the serial line

    // Park the cursor below the logo for the REPL prompt.
    cursor_col = 0;
    cursor_row = (oy + lh) / CHAR_H + 1;
    cursor_visible = 0;
    return 1;
}

// ---------------------------------------------------------------------------
// BBC-style graphics
//
// Logical coordinate space is 1280x1024 with the origin at the bottom-left,
// mapped onto the physical framebuffer. State: graphics foreground/background
// colours, the GCOL plot action, and a short history of the last three points
// (PLOT lines use the last two, triangles the last three, circles use the last
// two as centre + a point on the circumference).
// ---------------------------------------------------------------------------

#define GFX_LW 1280
#define GFX_LH 1024

// Current graphics target dimensions. gl_* is the logical coordinate extent and
// gt_* the destination pixel size; they differ only while SPRITETARGET is active
// (both become the sprite's size, so drawing addresses sprite pixels directly).
static int gl_w(void) { return g_gl_w; }
static int gl_h(void) { return g_gl_h; }
static int gt_w(void) { return g_tgt_w > 0 ? g_tgt_w : (int)g_fb_w; }
static int gt_h(void) { return g_tgt_h > 0 ? g_tgt_h : (int)g_fb_h; }

static int gfx_fg  = 7;     // graphics foreground (logical colour)
static int gfx_bg  = 0;     // graphics background
static int gfx_act = 0;     // GCOL plot action (0=store 1=OR 2=AND 3=EOR 4=invert)
// RGB truecolour override: when *_true is set, drawing uses the 24-bit *_col
// instead of the 8-entry logical palette.
static int      gfx_fg_true = 0;
static uint32_t gfx_fg_col  = 0;
static int      gfx_bg_true = 0;
static uint32_t gfx_bg_col  = 0;
static uint32_t gcol_fg(void) { return gfx_fg_true ? gfx_fg_col : bbc_palette[gfx_fg & 7]; }
static uint32_t gcol_bg(void) { return gfx_bg_true ? gfx_bg_col : bbc_palette[gfx_bg & 7]; }
static int gpx0, gpy0;      // most recent point (logical, origin-relative)
static int gpx1, gpy1;      // previous point
static int gpx2, gpy2;      // the one before that
static int gfx_ox = 0, gfx_oy = 0;   // graphics origin (VDU 29 / ORIGIN)

static int lx2px(int x) { return (x + gfx_ox) * gt_w()  / gl_w(); }
static int ly2py(int y) { return (gt_h() - 1) - ((y + gfx_oy) * gt_h() / gl_h()); }
// Inverse transforms (physical pixel -> logical, origin-relative).
static int px2lx(int px) { return px * gl_w() / gt_w() - gfx_ox; }
static int py2ly(int py) { return (gt_h() - 1 - py) * gl_h() / gt_h() - gfx_oy; }

static int isqrt_i(int v) {
    if (v <= 0) return 0;
    int r = 0;
    while ((r + 1) * (r + 1) <= v) r++;
    return r;
}

// Reset the default text/graphics viewports and graphics origin (VDU 26).
static void reset_viewports(void) {
    tv_l = 0; tv_t = 0; tv_r = g_term_cols - 1; tv_b = g_term_rows - 1;
    gfx_clear_clip();
    gfx_ox = 0; gfx_oy = 0;
    gpx0 = gpy0 = gpx1 = gpy1 = gpx2 = gpy2 = 0;
}

// Restore the default logical colours and palette (VDU 20).
static void reset_colours(void) {
    for (int i = 0; i < 8; i++) bbc_palette[i] = bbc_default_palette[i];
    text_color = bbc_palette[7];     // COLOUR 7
    text_bg    = bbc_palette[0];     // COLOUR 128
    gfx_fg = 7; gfx_bg = 0; gfx_act = 0;
    gfx_fg_true = 0; gfx_bg_true = 0;
    gfx_set_op(0);
}

void con_mode(int n) {
    (void)n;                                  // resolution is fixed; MODE just resets
    reset_colours();
    reset_viewports();
    vdu5_mode = 0; vdu_enabled = 1; cursor_enabled = 1;
    if (fb_ready) cleardevice();
    cursor_col = 0; cursor_row = 0; cursor_visible = 0;
    uart_puts("\r\n");
}

void con_gcol(int action, int colour) {
    gfx_act = action & 7;
    if (colour >= 128) { gfx_bg = (colour - 128) & 7; gfx_bg_true = 0; }   // background
    else               { gfx_fg = colour & 7;         gfx_fg_true = 0; }   // foreground
}

// GCOL r,g,b : set the graphics foreground to a 24-bit truecolour.
void con_gcol_rgb(int r, int g, int b) {
    gfx_fg_true = 1;
    gfx_fg_col  = rgb_pixel(r, g, b);
}

// COLOUR l,r,g,b : redefine logical colour l's palette entry (like VDU 19).
void con_palette(int logical, int r, int g, int b) {
    bbc_palette[logical & 7] = rgb_pixel(r, g, b);
}

void con_clg(void) {
    if (!fb_ready) return;
    int x0, y0, x1, y1;
    gfx_clip_rect(&x0, &y0, &x1, &y1);         // clear only the graphics viewport
    gfx_set_op(0);
    // Clearing a sprite target resets it to fully transparent (alpha 0) so
    // untouched areas stay see-through; the screen clears to the gfx background.
    fill_rect(x0, y0, x1, y1, g_tgt_w > 0 ? 0x00000000u : gcol_bg());
}

void con_plot(int code, int x, int y) {
    if (!fb_ready) return;
    int absolute = code & 4;
    int cmode    = code & 3;        // 0=move 1=foreground 2=inverse 3=background
    int group    = code & 0xF8;

    int nx, ny;
    if (absolute) { nx = x;        ny = y;        }
    else          { nx = gpx0 + x; ny = gpy0 + y; }

    gpx2 = gpx1; gpy2 = gpy1;       // shift point history
    gpx1 = gpx0; gpy1 = gpy0;
    gpx0 = nx;   gpy0 = ny;

    if (group == 0 && cmode == 0) return;          // plain MOVE

    uint32_t col = (cmode == 3) ? gcol_bg() : gcol_fg();
    int op = (cmode == 2) ? 3 : gfx_act;           // inverse colour -> EOR
    gfx_set_op(op);

    int x0 = lx2px(gpx0), y0 = ly2py(gpy0);
    int x1 = lx2px(gpx1), y1 = ly2py(gpy1);
    int x2 = lx2px(gpx2), y2 = ly2py(gpy2);

    switch (group) {
        case 0:    draw_line(x1, y1, x0, y0, col); break;          // line
        case 64:   draw_line(x0, y0, x0, y0, col); break;          // single point
        case 80:   fill_triangle(x0, y0, x1, y1, x2, y2, col); break;   // triangle
        case 96:   fill_rect(x1, y1, x0, y0, col); break;          // rectangle
        case 144:                                                   // circle outline
        case 152: {                                                 // circle fill
            int dx = x0 - x1, dy = y0 - y1;
            int r  = isqrt_i(dx * dx + dy * dy);
            if (group == 152) fill_circle(x1, y1, r, col);
            else              draw_circle(x1, y1, r, col);
            break;
        }
        default:   draw_line(x1, y1, x0, y0, col); break;          // fallback: line
    }
    gfx_set_op(0);                                  // leave op at store
}

int con_point(int x, int y) {
    if (!fb_ready) return -1;
    if (x < 0 || x >= gl_w() || y < 0 || y >= gl_h()) return -1;
    uint32_t px = getpixel(lx2px(x), ly2py(y));
    for (int i = 0; i < 8; i++) if (bbc_palette[i] == px) return i;
    return -1;
}

// --- double buffering -------------------------------------------------------
// The graphics driver owns the back buffer and the draw-target indirection; the
// console just gates it on a live framebuffer and keeps the software mouse
// pointer off the back buffer (it belongs on the visible screen only).
int con_backbuffer(int on) {
    if (!fb_ready) return on ? -1 : 0;
    if (on) {
        pointer_hide();                 // clear the arrow from the front first
        return gfx_backbuffer(1);
    }
    gfx_backbuffer(0);
    return 0;
}
void con_flip(void) { if (fb_ready) gfx_flip(); }
int  con_buffered(void) { return gfx_buffered(); }

// --- high-level shape commands (BBC logical coordinates) --------------------
// All draw in the current graphics foreground (logical or truecolour) and honour
// the GCOL plot op. Filled variants pass fill != 0.

void con_line(int x1, int y1, int x2, int y2) {
    if (!fb_ready) return;
    gfx_set_op(gfx_act);
    draw_line(lx2px(x1), ly2py(y1), lx2px(x2), ly2py(y2), gcol_fg());
    gfx_set_op(0);
    gpx0 = x2; gpy0 = y2;                 // leave the graphics cursor at the end
}

// RECTANGLE x,y,w,h : (x,y) is a corner, w/h are width/height in logical units.
void con_rectangle(int x, int y, int w, int h, int fill) {
    if (!fb_ready) return;
    int x0 = lx2px(x), y0 = ly2py(y), x1 = lx2px(x + w), y1 = ly2py(y + h);
    gfx_set_op(gfx_act);
    if (fill) fill_rect(x0, y0, x1, y1, gcol_fg());
    else      draw_rect(x0, y0, x1, y1, gcol_fg());
    gfx_set_op(0);
}

void con_circle(int x, int y, int r, int fill) {
    if (!fb_ready) return;
    int cx = lx2px(x), cy = ly2py(y);
    int rp = r * gt_w() / gl_w();                  // scale to a round radius in target pixels
    if (rp < 0) rp = -rp;
    gfx_set_op(gfx_act);
    if (fill) fill_circle(cx, cy, rp, gcol_fg());
    else      draw_circle(cx, cy, rp, gcol_fg());
    gfx_set_op(0);
}

void con_ellipse(int x, int y, int rx, int ry, int fill) {
    if (!fb_ready) return;
    int cx = lx2px(x), cy = ly2py(y);
    int rpx = rx * gt_w() / gl_w();
    int rpy = ry * gt_h() / gl_h();
    gfx_set_op(gfx_act);
    if (fill) fill_ellipse(cx, cy, rpx, rpy, gcol_fg());
    else      draw_ellipse(cx, cy, rpx, rpy, gcol_fg());
    gfx_set_op(0);
}

void con_fill(int x, int y) {
    if (!fb_ready) return;
    flood_fill(lx2px(x), ly2py(y), gcol_fg());
}

// --- sprites (screen-rectangle capture / stamp via a DIM buffer) ------------
// Layout at `addr`: 4 bytes width, 4 bytes height (little-endian), then
// width*height pixels of 4 bytes each (framebuffer format), top row first.
// Bytes are accessed one at a time to stay safe under -mstrict-align.
static void sp_wr32(volatile unsigned char *p, uint32_t v) {
    p[0] = v; p[1] = v >> 8; p[2] = v >> 16; p[3] = v >> 24;
}
static uint32_t sp_rd32(volatile unsigned char *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) |
           ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}

// --- sprite tint (GTINT) ----------------------------------------------------
// A drawing-state colour that every blitted sprite is lerped toward, like GCOL.
static int g_tint_on = 0, g_tint_r = 0, g_tint_g = 0, g_tint_b = 0, g_tint_a = 0;

void con_sprite_tint(int on, int r, int g, int b, int a) {
    g_tint_on = on ? 1 : 0;
    g_tint_r = r & 0xff; g_tint_g = g & 0xff; g_tint_b = b & 0xff;
    g_tint_a = a < 0 ? 0 : a > 255 ? 255 : a;
}

// Lerp a source pixel toward the tint colour (out = lerp(src,(r,g,b),a/255)),
// keeping the source alpha so transparency is preserved.
static uint32_t tint_px(uint32_t src) {
    if (!g_tint_on || g_tint_a == 0) return src;
    unsigned a = (unsigned)g_tint_a, na = 255 - a;
    unsigned r = ( src        & 0xff);
    unsigned g = ((src >> 8)  & 0xff);
    unsigned b = ((src >> 16) & 0xff);
    r = (r * na + (unsigned)g_tint_r * a + 127) / 255;
    g = (g * na + (unsigned)g_tint_g * a + 127) / 255;
    b = (b * na + (unsigned)g_tint_b * a + 127) / 255;
    return (src & 0xFF000000u) | (b << 16) | (g << 8) | r;
}

// Blit one source pixel to (px,py): apply the tint, then honour the pixel's
// alpha (0 = skip, 255 = opaque through the current plot op, otherwise blend
// over the destination in store mode). The caller sets the plot op to gfx_act
// around the loop; this restores it after a blended (partial-alpha) pixel.
static void sp_put_pixel(int px, int py, uint32_t src) {
    src = tint_px(src);
    unsigned a = (src >> 24) & 0xFF;
    if (a == 0) return;
    if (a == 255) { putpixel_op(px, py, src); return; }
    uint32_t dst = getpixel(px, py);
    unsigned na = 255 - a;
    unsigned r = (( src        & 0xff) * a + ( dst        & 0xff) * na + 127) / 255;
    unsigned g = (((src >> 8)  & 0xff) * a + ((dst >> 8)  & 0xff) * na + 127) / 255;
    unsigned b = (((src >> 16) & 0xff) * a + ((dst >> 16) & 0xff) * na + 127) / 255;
    gfx_set_op(0);
    putpixel_op(px, py, 0xFF000000u | (b << 16) | (g << 8) | r);
    gfx_set_op(gfx_act);
}

// Minimal sine/cosine for sprite rotation (the kernel has no libm). Argument in
// radians; range-reduced to [-pi/4,pi/4] with a short Taylor series - ample for
// a nearest-sample blit. Ported from the interpreter's dsin().
#define K_PI 3.14159265358979323846
static double k_sin(double x) {
    double twopi = 2 * K_PI, halfpi = K_PI / 2;
    double kq = x / twopi;   kq = (double)(long)(kq >= 0 ? kq + 0.5 : kq - 0.5);
    x -= kq * twopi;
    double nq = x / halfpi;  int n = (int)(nq >= 0 ? nq + 0.5 : nq - 0.5);
    double r = x - n * halfpi, r2 = r * r;
    double st = r, ss = r;
    for (int i = 1; i < 8; i++) { st *= -r2 / ((2 * i) * (2 * i + 1)); ss += st; }
    double ct = 1, cc = 1;
    for (int i = 1; i < 8; i++) { ct *= -r2 / ((2 * i - 1) * (2 * i)); cc += ct; }
    switch (((n % 4) + 4) % 4) {
        case 0:  return ss;
        case 1:  return cc;
        case 2:  return -ss;
        default: return -cc;
    }
}
static double k_cos(double x) { return k_sin(x + K_PI / 2); }

void con_sprite_get(long addr, int x1, int y1, int x2, int y2) {
    if (!fb_ready || !addr) return;
    int px1 = lx2px(x1), py1 = ly2py(y1), px2 = lx2px(x2), py2 = ly2py(y2);
    if (px1 > px2) { int t = px1; px1 = px2; px2 = t; }
    if (py1 > py2) { int t = py1; py1 = py2; py2 = t; }
    int w = px2 - px1 + 1, h = py2 - py1 + 1;
    volatile unsigned char *p = (volatile unsigned char *)(uintptr_t)addr;
    sp_wr32(p, (uint32_t)w);
    sp_wr32(p + 4, (uint32_t)h);
    volatile unsigned char *q = p + 8;
    for (int row = 0; row < h; row++)
        for (int col = 0; col < w; col++) {
            sp_wr32(q, getpixel(px1 + col, py1 + row));
            q += 4;
        }
}

// (x,y) is the logical point where the sprite's top-left corner is placed. Each
// pixel's alpha (the high byte) controls transparency: 0 = fully transparent
// (skipped, so the background shows through), 255 = opaque (drawn through the
// current plot op, so EOR animation still works), values in between are
// alpha-blended over the current screen pixel. GGET captures and images without
// an alpha channel store 255 everywhere, so they draw fully opaque as before.
void con_sprite_put(long addr, int x, int y) {
    if (!fb_ready || !addr) return;
    volatile unsigned char *p = (volatile unsigned char *)(uintptr_t)addr;
    int w = (int)sp_rd32(p), h = (int)sp_rd32(p + 4);
    if (w <= 0 || h <= 0 || w > gt_w() || h > gt_h()) return;
    int dx = lx2px(x), dy = ly2py(y);
    volatile unsigned char *q = p + 8;
    gfx_set_op(gfx_act);
    for (int row = 0; row < h; row++)
        for (int col = 0; col < w; col++) {
            uint32_t src = sp_rd32(q); q += 4;
            sp_put_pixel(dx + col, dy + row, src);         // tint + alpha + plot op
        }
    gfx_set_op(0);
}

// Blit a sprite scaled by `scale` and rotated `angle` degrees clockwise about
// its centre, that centre placed where the plain con_sprite_put's centre would
// land - so (scale=1, angle=0) matches con_sprite_put. Destination-driven with
// nearest sampling: for each output pixel we inverse-map back into the sprite.
void con_sprite_put_ex(long addr, int x, int y, double scale, double angle) {
    if (!fb_ready || !addr || scale <= 0) return;
    volatile unsigned char *p = (volatile unsigned char *)(uintptr_t)addr;
    int w = (int)sp_rd32(p), h = (int)sp_rd32(p + 4);
    if (w <= 0 || h <= 0) return;
    volatile unsigned char *pix = p + 8;

    double hw = w * 0.5, hh = h * 0.5;
    double cx = lx2px(x) + hw, cy = ly2py(y) + hh;         // sprite centre (physical)
    double rad = angle * (K_PI / 180.0);
    double c = k_cos(rad), s = k_sin(rad);
    double ac = c < 0 ? -c : c, as = s < 0 ? -s : s;
    // Tight half-extents of the scaled+rotated bounding box.
    int Rx = (int)(scale * (hw * ac + hh * as)) + 1;
    int Ry = (int)(scale * (hw * as + hh * ac)) + 1;

    gfx_set_op(gfx_act);
    for (int oy = -Ry; oy <= Ry; oy++)
        for (int ox = -Rx; ox <= Rx; ox++) {
            // Inverse transform (dest offset -> source offset), then to a pixel.
            double u = ( ox * c + oy * s) / scale + hw;
            double v = (-ox * s + oy * c) / scale + hh;
            if (u < 0 || v < 0) continue;
            int col = (int)u, row = (int)v;
            if (col >= w || row >= h) continue;
            uint32_t src = sp_rd32(pix + (((row * w) + col) << 2));
            sp_put_pixel((int)(cx + ox), (int)(cy + oy), src);
        }
    gfx_set_op(0);
}

// --- TrueType text (GTEXT) --------------------------------------------------
// Draw a string with the current TrueType font (see ttf.c). (x,y) is the logical
// coordinate of the baseline at the start of the run; the pen advances in
// physical pixels so glyphs stay crisp at their native size regardless of the
// logical-to-physical scale. Each glyph's 8-bit coverage becomes a source pixel
// (coverage as alpha, the graphics foreground as colour) and goes through
// sp_put_pixel, so tint, plot op, viewport and the current draw target apply just
// as for a sprite. Synthetic italic shears each row; underline draws a rule below
// the baseline after the run. (Bold is baked into the coverage by ttf.c.)
// Blit a run of the current TrueType font with its baseline start at physical
// pixel (px,py), in framebuffer colour `fg`. Shared by con_gtext (BASIC's GTEXT,
// logical coords) and sgfx_text (native seeds, device pixels).
static void gtext_blit(int px, int py, const char *s, int len, uint32_t fg) {
    if (!fb_ready || !s || len <= 0 || !ttf_ready()) return;
    int flags   = ttf_style_flags();
    int italic  = flags & 2;
    int underln = flags & 4;
    uint32_t rgb = fg & 0x00FFFFFFu;             // colour bytes; alpha set per pixel

    int penx = px;
    gfx_set_op(gfx_act);
    for (int i = 0; i < len; i++) {
        const unsigned char *bmp; int gw, gh, gx, gy, adv;
        if (!ttf_glyph((unsigned char)s[i], &bmp, &gw, &gh, &gx, &gy, &adv)) break;
        if (bmp && gw > 0 && gh > 0) {
            for (int row = 0; row < gh; row++) {
                int yy = py + gy + row;
                int shear = italic ? (int)(-(gy + row) * 0.2) : 0;   // ascenders lean right
                const unsigned char *srow = bmp + row * gw;
                for (int col = 0; col < gw; col++) {
                    unsigned cov = srow[col];
                    if (!cov) continue;
                    sp_put_pixel(penx + gx + col + shear, yy, ((uint32_t)cov << 24) | rgb);
                }
            }
        }
        penx += adv;
    }
    gfx_set_op(0);

    if (underln && penx > px) {                  // rule two pixels below the baseline
        int uy = py + 2;
        for (int xx = px; xx < penx; xx++) putpixel_op(xx, uy, fg);
    }
}

// Draw a string with the current TrueType font (see ttf.c). (x,y) is the logical
// coordinate of the baseline at the start of the run; glyphs are anti-aliased and
// honour tint, plot op, viewport and the current draw target, just like a sprite.
void con_gtext(int x, int y, const char *s, int len) {
    gtext_blit(lx2px(x), ly2py(y), s, len, gcol_fg());
}

// --- device-pixel graphics for native seeds (gfx.h / BGI-style, ABI v7) ------
// These address the framebuffer directly: origin top-left, colours 0xRRGGBB.
// They forward to the graphics.c primitives (which honour the clip rectangle and
// the current draw target), so a seed's output composes with BASIC's graphics.
// The plot op rests at 0 (store) between BASIC statements, which is the copy mode
// BGI drawing expects.
static uint32_t rgb_to_fb(uint32_t rgb) {
    return rgb_pixel((rgb >> 16) & 0xff, (rgb >> 8) & 0xff, rgb & 0xff);
}
static uint32_t fb_to_rgb(uint32_t px) {
    return (((px & 0xff) << 16) | (px & 0xff00) | ((px >> 16) & 0xff));   // R,G,B swap
}

int  sgfx_avail(void)  { return fb_ready ? 1 : 0; }
int  sgfx_width(void)  { return (int)g_fb_w; }
int  sgfx_height(void) { return (int)g_fb_h; }

void sgfx_clear(uint32_t rgb) {
    if (fb_ready) bar(0, 0, (int)g_fb_w - 1, (int)g_fb_h - 1, rgb_to_fb(rgb));
}
void sgfx_putpixel(int x, int y, uint32_t rgb) { if (fb_ready) putpixel(x, y, rgb_to_fb(rgb)); }
uint32_t sgfx_getpixel(int x, int y) { return fb_ready ? fb_to_rgb(getpixel(x, y)) : 0; }

void sgfx_line(int x1, int y1, int x2, int y2, uint32_t rgb) {
    if (fb_ready) draw_line(x1, y1, x2, y2, rgb_to_fb(rgb));
}
void sgfx_fillrect(int x1, int y1, int x2, int y2, uint32_t rgb) {
    if (fb_ready) fill_rect(x1, y1, x2, y2, rgb_to_fb(rgb));
}
void sgfx_circle(int cx, int cy, int r, uint32_t rgb)      { if (fb_ready) draw_circle(cx, cy, r, rgb_to_fb(rgb)); }
void sgfx_fillcircle(int cx, int cy, int r, uint32_t rgb)  { if (fb_ready) fill_circle(cx, cy, r, rgb_to_fb(rgb)); }
void sgfx_ellipse(int cx, int cy, int rx, int ry, uint32_t rgb)     { if (fb_ready) draw_ellipse(cx, cy, rx, ry, rgb_to_fb(rgb)); }
void sgfx_fillellipse(int cx, int cy, int rx, int ry, uint32_t rgb) { if (fb_ready) fill_ellipse(cx, cy, rx, ry, rgb_to_fb(rgb)); }
void sgfx_flood(int x, int y, uint32_t rgb) { if (fb_ready) flood_fill(x, y, rgb_to_fb(rgb)); }

void sgfx_clip(int x1, int y1, int x2, int y2) { if (fb_ready) gfx_set_clip(x1, y1, x2, y2); }
void sgfx_noclip(void)                         { if (fb_ready) gfx_clear_clip(); }

// Scanline fill of an arbitrary (convex or concave) polygon, even-odd rule.
void sgfx_fillpoly(const int *xy, int npts, uint32_t rgb) {
    if (!fb_ready || npts < 3 || !xy) return;
    uint32_t c = rgb_to_fb(rgb);
    int ymin = xy[1], ymax = xy[1];
    for (int i = 1; i < npts; i++) { int y = xy[i * 2 + 1]; if (y < ymin) ymin = y; if (y > ymax) ymax = y; }
    if (ymin < 0) ymin = 0;
    if (ymax > (int)g_fb_h - 1) ymax = (int)g_fb_h - 1;
    for (int y = ymin; y <= ymax; y++) {
        int xs[64], nx = 0;
        for (int i = 0; i < npts; i++) {
            int j = (i + 1) % npts;
            int y0 = xy[i * 2 + 1], y1 = xy[j * 2 + 1];
            int x0 = xy[i * 2],     x1 = xy[j * 2];
            if ((y0 <= y && y1 > y) || (y1 <= y && y0 > y)) {   // half-open crossing
                int xc = x0 + (int)((long)(y - y0) * (x1 - x0) / (y1 - y0));
                if (nx < 64) xs[nx++] = xc;
            }
        }
        for (int a = 0; a < nx - 1; a++)                        // insertion-ish sort
            for (int b = a + 1; b < nx; b++)
                if (xs[b] < xs[a]) { int t = xs[a]; xs[a] = xs[b]; xs[b] = t; }
        for (int k = 0; k + 1 < nx; k += 2)
            for (int x = xs[k]; x <= xs[k + 1]; x++) putpixel(x, y, c);
    }
}

// Draw TrueType text at device pixel (x,y) (baseline start) in colour rgb, in
// copy mode (the seed's colour wins regardless of BASIC's GCOL action).
void sgfx_text(int x, int y, const char *s, int len, uint32_t rgb) {
    if (!fb_ready) return;
    int save = gfx_act; gfx_act = 0;
    gtext_blit(x, y, s, len, rgb_to_fb(rgb));
    gfx_act = save;
}

// --- render-to-sprite (NEWSPRITE / SPRITETARGET) ----------------------------
// Initialise a DIM buffer as a w*h fully transparent sprite (8-byte header then
// zeroed - alpha 0 - pixels). Bytes written one at a time to stay alignment-safe.
void con_newsprite(long addr, int w, int h) {
    if (!addr || w <= 0 || h <= 0) return;
    volatile unsigned char *p = (volatile unsigned char *)(uintptr_t)addr;
    sp_wr32(p, (uint32_t)w);
    sp_wr32(p + 4, (uint32_t)h);
    volatile unsigned char *q = p + 8;
    long n = (long)w * h;
    for (long i = 0; i < n; i++) { sp_wr32(q, 0); q += 4; }
}

// Redirect all drawing into sprite `addr`: the graphics driver writes the
// sprite's pixel area (aligned 32-bit stores; the DIM heap is 16-aligned) and
// the coordinate space becomes the sprite's own pixels, origin bottom-left.
int con_target_sprite(long addr) {
    if (!fb_ready || !addr) return -1;
    volatile unsigned char *p = (volatile unsigned char *)(uintptr_t)addr;
    int w = (int)sp_rd32(p), h = (int)sp_rd32(p + 4);
    if (w <= 0 || h <= 0) return -1;
    pointer_hide();                              // keep the arrow off the sprite
    gfx_set_target((uint32_t *)(uintptr_t)(addr + 8), (uint32_t)w, (uint32_t)h);
    g_tgt_w = w; g_tgt_h = h;
    g_gl_w  = w; g_gl_h  = h;                    // 1:1 pixel coordinates
    return 0;
}

// Return drawing to the screen (or the back buffer, if BUFFER ON).
void con_target_screen(void) {
    gfx_reset_target();
    g_tgt_w = 0; g_tgt_h = 0;
    g_gl_w  = GFX_LW; g_gl_h = GFX_LH;
}

// --- tilemap ----------------------------------------------------------------
// Draw the visible window of a tile grid in one call. `map` -> cols*rows LE u32
// words, row-major (top row first); value 0 = empty (skipped), k>=1 = sheet tile
// (k-1). Tiles are tilew x tileh, packed row-major in the `sheet` sprite;
// scrollx/scrolly shift the world left/up. Positions are target pixels, origin
// top-left; clipped to the viewport, honouring alpha, the plot op and the tint.
void con_tilemap(long sheet, long map, int cols, int rows,
                 int tilew, int tileh, int scrollx, int scrolly) {
    if (!fb_ready || !sheet || !map) return;
    if (cols <= 0 || rows <= 0 || tilew <= 0 || tileh <= 0) return;
    volatile unsigned char *sp = (volatile unsigned char *)(uintptr_t)sheet;
    int sw = (int)sp_rd32(sp), sh = (int)sp_rd32(sp + 4);
    if (sw <= 0 || sh <= 0) return;
    int tpr = sw / tilew;                          // tiles per sheet row
    if (tpr <= 0) return;
    volatile unsigned char *spix = sp + 8;
    volatile unsigned char *mp   = (volatile unsigned char *)(uintptr_t)map;

    int vx0, vy0, vx1, vy1;
    gfx_clip_rect(&vx0, &vy0, &vx1, &vy1);         // viewport in target pixels

    // Loose range of visible cells; the per-pixel clip below handles exact edges.
    int c_lo = (vx0 + scrollx) / tilew - 1, c_hi = (vx1 + scrollx) / tilew + 1;
    int r_lo = (vy0 + scrolly) / tileh - 1, r_hi = (vy1 + scrolly) / tileh + 1;
    if (c_lo < 0) c_lo = 0;
    if (r_lo < 0) r_lo = 0;
    if (c_hi > cols - 1) c_hi = cols - 1;
    if (r_hi > rows - 1) r_hi = rows - 1;

    gfx_set_op(gfx_act);
    for (int mr = r_lo; mr <= r_hi; mr++) {
        int dy0 = mr * tileh - scrolly;            // tile top on screen (top-left origin)
        for (int mc = c_lo; mc <= c_hi; mc++) {
            uint32_t idx = sp_rd32(mp + ((((long)mr * cols) + mc) << 2));
            if (idx == 0) continue;                // empty cell: transparent
            int t = (int)idx - 1;
            int ssx = (t % tpr) * tilew, ssy = (t / tpr) * tileh;
            if (ssy + tileh > sh) continue;        // tile index past the sheet: skip
            int dx0 = mc * tilew - scrollx;
            for (int py = 0; py < tileh; py++) {
                int dy = dy0 + py;
                if (dy < vy0 || dy > vy1) continue;
                volatile unsigned char *srow = spix + ((((long)(ssy + py) * sw) + ssx) << 2);
                for (int px = 0; px < tilew; px++) {
                    int dx = dx0 + px;
                    if (dx < vx0 || dx > vx1) continue;
                    sp_put_pixel(dx, dy, sp_rd32(srow + (px << 2)));
                }
            }
        }
    }
    gfx_set_op(0);
}

// ---------------------------------------------------------------------------
// VDU driver - interprets a byte stream as the BBC Micro's VDU does. The BASIC
// VDU statement feeds each byte here; control codes 0..31 (and 127) act on the
// screen, consuming a fixed number of following parameter bytes; codes >= 32 are
// printable characters. See the VDU code summary for what each does.
// ---------------------------------------------------------------------------

// Parameter bytes consumed by each control code 0..31.
static const unsigned char vdu_nparams[32] = {
    0,1,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,
    0,1,2,5,0,0,1,9, 8,5,0,1,4,4,0,2
};
static uint8_t vdu_q[16];
static int vdu_qn = 0, vdu_qneed = 0, vdu_cmd = -1;

static int vdu_word(int i)  { return vdu_q[i] | (vdu_q[i+1] << 8); }
static int vdu_sword(int i) { int v = vdu_word(i); return v >= 32768 ? v - 65536 : v; }
static int gfx_char_w(void) { return CHAR_W * gl_w() / gt_w(); }
static int gfx_char_h(void) { return CHAR_H * gl_h() / gt_h(); }
static int clampi(int v, int lo, int hi) { return v < lo ? lo : v > hi ? hi : v; }

// --- VDU 5: text at the graphics cursor -------------------------------------
// Logical coordinates of the left and top edges of the graphics viewport (the
// whole screen unless VDU 24 set one), used as the "home" / line-start position.
static int gfx_vp_left(void) { int x0,y0,x1,y1; gfx_clip_rect(&x0,&y0,&x1,&y1); return px2lx(x0); }
static int gfx_vp_top(void)  { int x0,y0,x1,y1; gfx_clip_rect(&x0,&y0,&x1,&y1); return py2ly(y0); }

// Draw one glyph at the graphics cursor: the cursor is the TOP-LEFT of the cell,
// plotted in the graphics foreground colour using the current GCOL plot action,
// with a transparent background, clipped to the graphics viewport. Then advance
// the graphics cursor right by one character width.
static void gfx_text_char(unsigned char uc) {
    gfx_set_op(gfx_act);
    draw_glyph_op(&bbc_font[uc * GLYPH_BYTES], lx2px(gpx0), ly2py(gpy0), FONT_SCALE,
                  bbc_palette[gfx_fg & 7]);
    gfx_set_op(0);
    gpx0 += gfx_char_w();
}
static void gfx_text_cr(void) { gpx0 = gfx_vp_left(); }
static void gfx_text_lf(void) { gpy0 -= gfx_char_h(); }
static void gfx_text_bs(void) { gpx0 -= gfx_char_w(); }

// Output a printable character: at the graphics cursor in VDU 5 mode, otherwise
// at the text cursor (mirrored to serial like PRINT).
static void vdu_putchar(int uc) {
    if (cursor_visible) cursor_set(0);
    if (vdu5_mode) gfx_text_char((unsigned char)uc);
    else           term_glyph((unsigned char)uc);
    // VDU-statement characters don't pass through con_putc, so mirror them to the
    // serial console here (PRINT-driven characters are mirrored by con_putc).
    if (uc >= 32 && uc < 127) uart_putc((char)uc);
}

static void vdu_del(void) {
    if (!fb_ready) return;
    if (cursor_visible) cursor_set(0);
    if (vdu5_mode) {                          // VDU 5: backspace + erase at gfx cursor
        gpx0 -= gfx_char_w();                 // ... using the graphics background colour
        int px = lx2px(gpx0), py = ly2py(gpy0);
        gfx_set_op(0);
        fill_rect(px, py, px + CHAR_W - 1, py + CHAR_H - 1, bbc_palette[gfx_bg & 7]);
        return;
    }
    if (cursor_col > tv_l) --cursor_col;
    else if (cursor_row > tv_t) { --cursor_row; cursor_col = tv_r; }
    else return;
    bar(cursor_col * CHAR_W, cursor_row * CHAR_H,
        cursor_col * CHAR_W + CHAR_W - 1, cursor_row * CHAR_H + CHAR_H - 1, text_bg);
}

static void vdu_execute(int cmd) {
    // When output is disabled (VDU 21) only VDU 6 (re-enable) is acted upon.
    if (!vdu_enabled && cmd != 6) return;
    if (cursor_visible && cmd < 32) cursor_set(0);

    switch (cmd) {
        case 0:  break;                                   // null
        case 1:  break;                                   // -> printer only (no printer)
        case 2:  case 3: break;                           // printer enable/disable (none)
        case 4:  vdu5_mode = 0; break;                    // text at text cursor
        case 5:  vdu5_mode = 1; break;                    // text at graphics cursor
        case 6:  vdu_enabled = 1; break;                  // enable screen output
        case 7:  break;                                   // bell (no audio)
        case 8:  if (vdu5_mode) gpx0 -= gfx_char_w();      // cursor left
                 else if (cursor_col > tv_l) cursor_col--;
                 else if (cursor_row > tv_t) { cursor_row--; cursor_col = tv_r; }
                 break;
        case 9:  if (vdu5_mode) gpx0 += gfx_char_w();      // cursor right
                 else if (cursor_col < tv_r) cursor_col++;
                 else term_advance();
                 break;
        case 10: if (vdu5_mode) gpy0 -= gfx_char_h();      // cursor down (LF)
                 else { if (++cursor_row > tv_b) { scroll_rect(tv_l*CHAR_W, tv_t*CHAR_H,
                            (tv_r+1)*CHAR_W-1, (tv_b+1)*CHAR_H-1, CHAR_H, text_bg);
                            cursor_row = tv_b; } }
                 break;
        case 11: if (vdu5_mode) gpy0 += gfx_char_h();      // cursor up
                 else if (cursor_row > tv_t) cursor_row--;
                 break;
        case 12: con_cls(); break;                         // clear text (CLS)
        case 13: if (vdu5_mode) gfx_text_cr();             // carriage return
                 else cursor_col = tv_l;
                 break;
        case 14: case 15: break;                           // auto-paging (not implemented)
        case 16: con_clg(); break;                         // clear graphics (CLG)
        case 17: con_colour(vdu_q[0]); break;              // COLOUR
        case 18: con_gcol(vdu_q[0], vdu_q[1]); break;      // GCOL
        case 19: {                                         // palette
            int l = vdu_q[0] & 7, p = vdu_q[1];
            if (p == 16)       bbc_palette[l] = rgb_pixel(vdu_q[2], vdu_q[3], vdu_q[4]);
            else if (p == 255) bbc_palette[l] = rgb_pixel(vdu_q[2]*4, vdu_q[3]*4, vdu_q[4]*4);
            else               bbc_palette[l] = bbc_default_palette[p & 7];
            break;
        }
        case 20: reset_colours(); break;                   // default colours + palette
        case 21: vdu_enabled = 0; break;                   // disable screen output
        case 22: con_mode(vdu_q[0]); break;                // MODE
        case 23: {                                         // user-defined char / control
            int sub = vdu_q[0];
            if (sub >= 32) {                               // redefine character `sub`
                // VDU 23 always carries 8 row bytes (r1..r8); copy as many as the
                // glyph holds (GLYPH_BYTES rows).
                for (int i = 0; i < 8 && i < GLYPH_BYTES; i++)
                    bbc_font[sub * GLYPH_BYTES + i] = vdu_q[1 + i];
            } else if (sub == 1) {                         // text cursor (caret) on/off
                cursor_enabled = (vdu_q[1] != 0);
                if (!cursor_enabled && cursor_visible) cursor_set(0);
            } else if (sub == 7) {                         // scroll the text viewport
                int d = vdu_q[2];                          // 0=right 1=left 2=down 3=up
                int dx = (d == 0) ? CHAR_W : (d == 1) ? -CHAR_W : 0;
                int dy = (d == 2) ? CHAR_H : (d == 3) ? -CHAR_H : 0;
                move_rect(tv_l * CHAR_W, tv_t * CHAR_H,
                          (tv_r + 1) * CHAR_W - 1, (tv_b + 1) * CHAR_H - 1,
                          dx, dy, text_bg);
            }
            // sub 0 (cursor appearance), 16 (cursor-movement flags), 18 (MODE 7),
            // 22 (user-defined screen modes) and 23 (line thickness) are parsed
            // but not implemented - they don't map to this fixed-mode display.
            break;
        }
        case 24:                                            // graphics viewport
            gfx_set_clip(lx2px(vdu_sword(0)), ly2py(vdu_sword(6)),
                         lx2px(vdu_sword(4)), ly2py(vdu_sword(2)));
            break;
        case 25: con_plot(vdu_q[0], vdu_sword(1), vdu_sword(3)); break;   // PLOT
        case 26: reset_viewports(); cursor_col = tv_l; cursor_row = tv_t; break;
        case 27: vdu_putchar(vdu_q[0]); break;             // print next byte literally
        case 28: {                                          // text viewport
            int l = clampi(vdu_q[0],0,g_term_cols-1), bm = clampi(vdu_q[1],0,g_term_rows-1);
            int r = clampi(vdu_q[2],0,g_term_cols-1), t  = clampi(vdu_q[3],0,g_term_rows-1);
            tv_l = l < r ? l : r; tv_r = l < r ? r : l;
            tv_t = t < bm ? t : bm; tv_b = t < bm ? bm : t;
            cursor_col = tv_l; cursor_row = tv_t;
            break;
        }
        case 29: gfx_ox = vdu_sword(0); gfx_oy = vdu_sword(2); break;   // ORIGIN
        case 30: if (vdu5_mode) { gpx0 = gfx_vp_left(); gpy0 = gfx_vp_top(); }  // home
                 else { cursor_col = tv_l; cursor_row = tv_t; }
                 break;
        case 31: cursor_col = clampi(tv_l + vdu_q[0], tv_l, tv_r);     // TAB(x,y)
                 cursor_row = clampi(tv_t + vdu_q[1], tv_t, tv_b);
                 break;
        default: break;
    }
}

void con_vdu(int b) {
    b &= 0xff;
    if (vdu_cmd >= 0) {                       // collecting parameter bytes
        vdu_q[vdu_qn++] = (uint8_t)b;
        if (vdu_qn < vdu_qneed) return;
        int cmd = vdu_cmd; vdu_cmd = -1;
        vdu_execute(cmd);
        return;
    }
    if (b < 32) {
        int need = vdu_nparams[b];
        if (need) { vdu_cmd = b; vdu_qn = 0; vdu_qneed = need; return; }
        vdu_execute(b);                       // zero-parameter control code
        return;
    }
    if (b == 127) { if (vdu_enabled) vdu_del(); return; }
    if (vdu_enabled) vdu_putchar(b);          // printable character
}

// ---------------------------------------------------------------------------
// Exception handler (called from the vector table in vectors.S)
// ---------------------------------------------------------------------------

// Print a labelled hex value straight to the framebuffer terminal (used by the
// exception handler so fault details are readable on screen even when the SD
// log write itself fails).
static void term_hexval(const char *label, uint64_t v, int digits) {
    term_puts(label);
    const char *h = "0123456789ABCDEF";
    for (int i = (digits - 1) * 4; i >= 0; i -= 4)
        term_putchar(h[(v >> i) & 0xF]);
    term_putchar('\n');
}

// Print the last `max_lines` lines of the in-RAM boot log to the framebuffer.
// Lets the exception handler show how far boot got (e.g. the [PCIE]/[XHCI]
// progress lines) on screen, without needing the SD card.
static void term_log_tail(int max_lines) {
    const char *buf; int len;
    uart_log_get(&buf, &len);
    int start = 0, nl = 0;
    for (int i = len - 1; i >= 0; i--) {
        if (buf[i] == '\n') { if (++nl > max_lines) { start = i + 1; break; } }
    }
    for (int i = start; i < len; i++) term_putchar(buf[i]);
}

void exception_handler(uint64_t type, uint64_t esr, uint64_t elr, uint64_t far) {
    static const char *vec_names[16] = {
        "SYNC/SP0",  "IRQ/SP0",  "FIQ/SP0",  "SERROR/SP0",
        "SYNC",      "IRQ",      "FIQ",       "SERROR",
        "SYNC/L64",  "IRQ/L64",  "FIQ/L64",   "SERROR/L64",
        "SYNC/L32",  "IRQ/L32",  "FIQ/L32",   "SERROR/L32",
    };
    uint32_t ec = (uint32_t)(esr >> 26) & 0x3F;
    const char *cause = "unknown";
    switch (ec) {
        case 0x00: cause = "unknown reason";       break;
        case 0x20: case 0x21: cause = "instruction abort"; break;
        case 0x22: cause = "PC alignment fault";   break;
        case 0x24: case 0x25: cause = "data abort"; break;
        case 0x26: cause = "SP alignment fault";   break;
        case 0x3C: cause = "BRK instruction";      break;
    }

    uart_puts("\n\n*** UNHANDLED EXCEPTION ***\n");
    uart_puts("vector : "); uart_puts(vec_names[type & 15]); uart_putc('\n');
    uart_puts("cause  : "); uart_puts(cause);                uart_putc('\n');
    uart_hex  ("ESR_EL1: ", (uint32_t)esr);
    uart_hex  ("  EC   : ", ec);
    uart_hex64("ELR_EL1: ", elr);   // faulting instruction
    uart_hex64("FAR_EL1: ", far);   // faulting address
    uart_puts("system halted.\n");

    // Paint the fault details straight onto the screen FIRST - this is just
    // framebuffer memory writes, so it works even when the SD/FAT path that
    // flush_boot_log() uses is itself wedged by the fault (e.g. a pending PCIe
    // SError that re-fires during the SD write). Read these off the screen.
    if (fb_ready) {
        fill_rect(0, 0, (int)g_fb_w - 1, (int)g_fb_h - 1, COLOR_BLACK);
        cursor_col = 0; cursor_row = 0; cursor_visible = 0;
        text_color = COLOR_WHITE;
        // Recent boot progress first (shows the [PCIE]/[XHCI] lines), then the
        // fault details at the bottom so they stay visible if the log scrolls.
        term_puts("--- recent log ---\n");
        term_log_tail(20);
        term_puts("*** EXCEPTION ***\n");
        term_puts("vector: "); term_puts(vec_names[type & 15]); term_putchar('\n');
        term_puts("cause : "); term_puts(cause); term_putchar('\n');
        term_hexval("ESR = ", esr, 8);
        term_hexval("ELR = ", elr, 16);
        term_hexval("FAR = ", far, 16);
    }

    // Then also try to dump the full log to the SD card (best-effort).
    flush_boot_log();
    // vectors.S halts the CPU after we return.
}

// ---------------------------------------------------------------------------
// Board identification
// ---------------------------------------------------------------------------

// Query and log the board serial (tag 0x00010004). Real Pi hardware returns a
// nonzero serial; QEMU's raspi4b leaves it 0. Returns 1 on real hardware. We use
// this to avoid touching the PCIe controller under QEMU, which does not model it
// (an access there raises an external abort).
static int board_real_hw(void) {
    mbox[0] = 9 * 4;
    mbox[1] = 0;
    mbox[2] = 0x00010004; mbox[3] = 8; mbox[4] = 0;   // get board serial
    mbox[5] = 0; mbox[6] = 0;
    mbox[7] = 0;                                       // end tag
    mbox[8] = 0;
    mbox_call();
    uart_hex("[BOARD] serial lo: ", mbox[5]);
    uart_hex("[BOARD] serial hi: ", mbox[6]);
    return (mbox[5] | mbox[6]) != 0;
}

// ---------------------------------------------------------------------------
// Framebuffer setup via mailbox
// ---------------------------------------------------------------------------

// Ask the GPU to (re)allocate the framebuffer at w x h, 32bpp, RGB order, and
// wire it into the graphics driver. Updates g_fb_* and the text grid. Returns 1
// on success. Shared by the boot path and by SCREEN (con_screen); the caller is
// responsible for (re-)marking the buffer non-cacheable once the MMU is up.
static int fb_configure(uint32_t w, uint32_t h) {
    mbox[ 0] = 35 * 4;
    mbox[ 1] = 0;
    mbox[ 2] = 0x00048003; mbox[ 3] = 8; mbox[ 4] = 8;   // set physical w/h
    mbox[ 5] = w;
    mbox[ 6] = h;
    mbox[ 7] = 0x00048004; mbox[ 8] = 8; mbox[ 9] = 8;   // set virtual w/h
    mbox[10] = w;
    mbox[11] = h;
    mbox[12] = 0x00048005; mbox[13] = 4; mbox[14] = 4;   // set depth
    mbox[15] = 32;
    // Force pixel order to RGB (1). Without this each platform uses its own
    // default - QEMU is RGB but the real Pi 4 firmware defaults to BGR, which
    // swaps red/blue and turns the raspberry logo purple. We pack pixels with red
    // in the low byte, which is the RGB order.
    mbox[16] = 0x00048006; mbox[17] = 4; mbox[18] = 4;   // set pixel order
    mbox[19] = 1;                                        // 1 = RGB
    mbox[20] = 0x00040001; mbox[21] = 8; mbox[22] = 8;   // allocate framebuffer
    mbox[23] = 4096;                                     // -> base address
    mbox[24] = 0;                                        // -> size
    mbox[25] = 0x00040008; mbox[26] = 4; mbox[27] = 4;   // get pitch
    mbox[28] = 0;                                        // -> pitch
    mbox[29] = 0;                                        // end tag

    int ok = mbox_call();
    uart_dec("[FB] mbox_call returned: ", (uint32_t)ok);
    uart_dec("[FB] width:  ", mbox[5]);
    uart_dec("[FB] height: ", mbox[6]);
    uart_hex("[FB] bus addr: ", mbox[23]);
    uart_dec("[FB] pitch:  ", mbox[28]);

    if (!ok || mbox[28] == 0) return 0;

    uint32_t fb_bus  = mbox[23];
    uint32_t fb_phys = fb_bus & 0x3FFFFFFF;  // strip VideoCore bus alias
    uint32_t pitch   = mbox[28];
    uint32_t fb_size = mbox[24];
    uint32_t *fb     = (uint32_t *)(uintptr_t)fb_phys;

    uart_hex("[FB] physical: ", fb_phys);
    g_fb_phys = fb_phys;
    g_fb_size = fb_size;
    g_fb_w    = mbox[5];                     // the GPU may round to a supported size
    g_fb_h    = mbox[6];
    g_term_cols = (int)g_fb_w / CHAR_W;
    g_term_rows = (int)g_fb_h / CHAR_H;
    init_graphics(fb, mbox[5], mbox[6], pitch);
    fb_ready = 1;
    return 1;
}

// SCREEN width,height : switch the display to a new resolution mid-session. A
// non-positive w or h means "restore the startup resolution". Returns 1 on
// success. Reconfigures the framebuffer, re-marks it non-cacheable for the live
// MMU, rebuilds the text grid, clears the screen and re-homes the cursor/pointer.
// A no-op (no clear) when the requested size already matches the current one, so
// restoring at the end of a program that never changed resolution costs nothing.
int con_screen(int w, int h) {
    if (!fb_ready) return 0;
    if (w <= 0 || h <= 0) { w = (int)g_start_w; h = (int)g_start_h; }
    if (w < 64)   w = 64;                        // keep the GPU request sane
    if (h < 64)   h = 64;
    if (w > 1920) w = 1920;
    if (h > 1080) h = 1080;
    if ((uint32_t)w == g_fb_w && (uint32_t)h == g_fb_h) return 1;   // already there

    if (!fb_configure((uint32_t)w, (uint32_t)h)) return 0;
    mmu_set_noncached(g_fb_phys, g_fb_size);   // the new buffer must be non-cacheable too

    reset_viewports();
    cleardevice();
    cursor_col = 0; cursor_row = 0; cursor_visible = 0;
    g_mouse_x = (int)g_fb_w / 2; g_mouse_y = (int)g_fb_h / 2;
    return 1;
}

int con_screen_w(void) { return (int)g_fb_w; }
int con_screen_h(void) { return (int)g_fb_h; }

static int setup_fb(void) {
    // Boot: bring the framebuffer up at the compile-time startup resolution and
    // remember it as the resolution SCREEN restores to. The MMU is still off here,
    // so the buffer is naturally coherent; kernel_main marks it non-cacheable once
    // the page tables exist.
    if (!fb_configure(FB_WIDTH, FB_HEIGHT)) return 0;
    g_start_w = g_fb_w;
    g_start_h = g_fb_h;
    return 1;
}

// ---------------------------------------------------------------------------
// Kernel entry
// ---------------------------------------------------------------------------

void kernel_main(void) {
    uart_init();
    uart_puts("\n[BOOT] RPi4 bare metal kernel started\n");

    // Bring the framebuffer up BEFORE enabling the MMU. With caches off the
    // framebuffer is naturally coherent with the GPU, and - crucially - this
    // gives us a screen to print on even if the MMU/cache bring-up is itself what
    // hangs on real silicon. boot_msg() mirrors progress to this screen once up,
    // so the last line you see is exactly where the kernel stopped.
    uart_puts("[FB] setting up framebuffer...\n");
    if (!setup_fb()) {
        uart_puts("[FB] ERROR: framebuffer setup failed\n");
    } else {
        cleardevice();
        boot_msg("[FB] framebuffer OK\n");
    }

    // Enable MMU + caches (big speed-up; also lets unaligned access work). On
    // real hardware this invalidates stale firmware cache state first.
    boot_msg("[MMU] enabling MMU + caches...\n");
    mmu_init();
    mmu_set_noncached(g_fb_phys, g_fb_size);   // re-mark FB NC (mmu_init rebuilt the tables)
    boot_msg("[MMU] enabled\n");

    // Show the BerryBasic boot logo (con_splash draws it when the REPL banner
    // prints; clearing the boot-progress text first).
    int real_hw = board_real_hw();
    g_real_hw = real_hw;                        // let the audio driver know (skips PWM on QEMU)
    g_show_logo = 1;

    // Mount the SD card (the data partition holds the user's BASIC programs).
    boot_msg("[SD] mounting filesystem...\n");
    g_sd_ready = (stg_init() == 0);
    boot_msg(g_sd_ready ? "[SD] mounted\n" : "[SD] mount FAILED\n");

    // USB keyboard on the DWC2 OTG / USB-C port (this is what QEMU emulates).
    // NOTE: on a board whose only USB-C port is power, no device is present here;
    // if boot visibly stops on the next line, the DWC2 probe is the culprit.
    boot_msg("[USB] initialising keyboard (DWC2/USB-C)...\n");
    g_kbd_ok = usb_kbd_init();
    boot_msg(g_kbd_ok ? "[USB] keyboard ready\n"
                      : "[USB] no USB-C keyboard\n");
    g_mouse_dwc2 = usb_mouse_present();
    if (g_mouse_dwc2) boot_msg("[USB] mouse ready (DWC2)\n");

    // On real hardware the USB-A ports are behind the VL805 xHCI on PCIe; bring
    // it up and look for a keyboard there too. QEMU does not model the PCIe
    // controller (touching it faults), so only do this on real hardware.
    if (!g_kbd_ok && real_hw) {
        boot_msg("[USB] trying USB-A (PCIe/VL805 xHCI)...\n");
        uintptr_t xhci_mmio = pcie_init();
        if (xhci_mmio) g_xhci_ok = xhci_kbd_init(xhci_mmio);
        boot_msg(g_xhci_ok ? "[USB] USB-A keyboard ready\n"
                           : "[USB] no USB-A keyboard\n");
        g_mouse_xhci = xhci_mouse_present();
        if (g_mouse_xhci) boot_msg("[USB] mouse ready (USB-A)\n");
    }

    // Select the configured keyboard layout (default US); a program can change
    // it at run time with the KEYBOARD statement.
    hid_set_layout(CFG_KBD_LAYOUT);

    // Write the full boot log to BOOTLOG.TXT on the data partition so USB
    // enumeration can be diagnosed on real hardware (no serial cable needed).
    flush_boot_log();

    // Hand control to the BASIC interpreter (runs forever on the target).
    boot_msg("[LOOP] entering BASIC\n");
    basic_init();
    basic_repl();
}
