#!/usr/bin/env bash
#
# Configure BerryBasic's native screen resolution and font, then regenerate the
# build inputs so a plain 'make' produces a kernel for the chosen setup:
#   - kernel/buildconfig.h   (resolution + glyph size + font scale)
#   - drivers/font_data.c     (the glyph table, converted from the chosen font file)
#   - boot/config.txt     (HDMI driven at the chosen resolution)
#
# Interactive:  tools/configure.sh
# Scripted:     tools/configure.sh 1024x768 fonts/ISO.F16 [scale]
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# --- 1. Resolution ----------------------------------------------------------
PRESETS=("640x480" "800x600" "1024x768" "1280x720" "1280x1024" "1920x1080")
RES="${1:-}"
if [ -z "$RES" ]; then
    echo "Native screen resolution:"
    i=0
    for r in "${PRESETS[@]}"; do i=$((i+1)); printf "  %d) %s\n" "$i" "$r"; done
    printf "  %d) custom (WIDTHxHEIGHT)\n" "$((i+1))"
    printf "Choose [1-%d]: " "$((i+1))"
    read -r c
    if [[ "$c" =~ ^[0-9]+$ ]] && [ "$c" -ge 1 ] && [ "$c" -le "${#PRESETS[@]}" ]; then
        RES="${PRESETS[$((c-1))]}"
    else
        printf "Enter resolution as WIDTHxHEIGHT: "; read -r RES
    fi
fi
RES="${RES,,}"                       # accept 800X600 too
WIDTH="${RES%x*}"; HEIGHT="${RES#*x}"
case "${WIDTH}-${HEIGHT}" in
    *[!0-9-]*|-*|*-) echo "error: bad resolution '$RES' (want WIDTHxHEIGHT)"; exit 1;;
esac

# --- 2. Font ----------------------------------------------------------------
FONT="${2:-}"
if [ -z "$FONT" ]; then
    mapfile -t FONTS < <(find fonts -maxdepth 1 -type f | sort)
    [ "${#FONTS[@]}" -gt 0 ] || { echo "error: no font files in fonts/"; exit 1; }
    echo
    echo "Font (from fonts/):"
    i=0
    for f in "${FONTS[@]}"; do
        i=$((i+1)); sz=$(stat -c %s "$f")
        if [ $((sz % 256)) -eq 0 ]; then h="8x$((sz/256))"; else h="(not 256 glyphs?)"; fi
        printf "  %d) %-16s %s\n" "$i" "$(basename "$f")" "$h"
    done
    printf "Choose [1-%d]: " "$i"; read -r c
    [[ "$c" =~ ^[0-9]+$ ]] && [ "$c" -ge 1 ] && [ "$c" -le "$i" ] || { echo "error: out of range"; exit 1; }
    FONT="${FONTS[$((c-1))]}"
fi
[ -f "$FONT" ] || { echo "error: font '$FONT' not found"; exit 1; }
FSIZE=$(stat -c %s "$FONT")
[ $((FSIZE % 256)) -eq 0 ] || { echo "error: '$FONT' is $FSIZE bytes, not 256 glyphs"; exit 1; }
GH=$((FSIZE / 256))                  # glyph height = file size / 256 glyphs

# --- 3. Font scale ----------------------------------------------------------
SCALE="${3:-}"
if [ -z "$SCALE" ]; then
    SCALE=2; [ "$GH" -ge 16 ] && SCALE=1   # taller fonts look right unscaled
fi
case "$SCALE" in 1|2|3) ;; *) echo "error: scale must be 1, 2 or 3"; exit 1;; esac

# --- 4. Generate kernel/buildconfig.h ------------------------------------------
cat > kernel/buildconfig.h <<EOF
#ifndef BUILDCONFIG_H
#define BUILDCONFIG_H

// ---------------------------------------------------------------------------
// Build-time configuration: screen resolution and font.
// GENERATED by tools/configure.sh - re-run that script to change it.
// ---------------------------------------------------------------------------

// Native framebuffer resolution (pixels). boot/config.txt drives HDMI to match.
#define CFG_FB_WIDTH   ${WIDTH}
#define CFG_FB_HEIGHT  ${HEIGHT}

// Glyph cell (source pixels) and draw magnification. The font is $(basename "$FONT").
#define CFG_GLYPH_W    8
#define CFG_GLYPH_H    ${GH}
#define CFG_FONT_SCALE ${SCALE}

#endif
EOF

# --- 5. Generate drivers/font_data.c from the chosen font -----------------------
tools/genfont.sh "$FONT" drivers/font_data.c

# --- 6. Patch the resolution block in boot/config.txt -----------------------
awk -v w="$WIDTH" -v h="$HEIGHT" '
    /^# >>> berrybasic-resolution/ {
        print
        print "hdmi_group=2"
        print "hdmi_mode=87"
        print "hdmi_cvt=" w " " h " 60"
        skip = 1; next
    }
    /^# <<< berrybasic-resolution/ { skip = 0 }
    !skip { print }
' boot/config.txt > boot/config.txt.new && mv boot/config.txt.new boot/config.txt

# --- 7. Force a clean rebuild (headers changed; the Makefile has no dep scan) -
rm -rf build

# --- 8. Summary -------------------------------------------------------------
COLS=$(( WIDTH  / (8  * SCALE) ))
ROWS=$(( HEIGHT / (GH * SCALE) ))
echo
echo "Configured:"
echo "  resolution : ${WIDTH}x${HEIGHT}"
echo "  font       : $(basename "$FONT")  (8x${GH}, scale ${SCALE} -> ${ROWS} rows x ${COLS} cols)"
echo
echo "Build it:   make            # then 'make run' (QEMU) or 'make flash' (hardware)"
