#!/bin/sh
# ---------------------------------------------------------------------------
# genconf.sh <output-conf.h>
#
# Generates conf.h: the startup COPYRIGHT_MESSAGE (the usual banner) expanded
# with build information (version, build date, git revision). It is #included by
# basic/basic.c and shared by every build of the interpreter (bare-metal kernel,
# host harness, and the CMake unit tests), so all three regenerate it the same
# way. The output path is passed in - each build writes it into its own BUILD
# directory (never the tracked source tree), so a build never dirties git.
#
# The file is rewritten ONLY when its contents actually change, so a rebuild of
# basic.o is not forced on every `make` (the date is day-granular; the git
# revision moves on commit / working-tree changes).
# ---------------------------------------------------------------------------
set -eu

OUT="${1:?usage: genconf.sh <output-conf.h>}"

# Version string (overridable from the environment / make command line).
VERSION="${BB_VERSION:-1.0}"

# Build date (day granularity keeps the header stable within a day).
DATE="$(date '+%Y-%m-%d')"

# Git revision: tag-relative describe if possible, else short hash, with a
# '-dirty' suffix when the working tree has uncommitted changes. Degrades to
# "nogit" for a tarball checkout with no repository.
REV="$(git describe --tags --always --dirty 2>/dev/null || echo nogit)"

TMP="${OUT}.tmp.$$"
cat > "$TMP" <<EOF
/* Generated by tools/genconf.sh - DO NOT EDIT (regenerated by the build). */
#ifndef CONF_H
#define CONF_H

#define BB_VERSION       "$VERSION"
#define BB_BUILD_DATE    "$DATE"
#define BB_GIT_REV       "$REV"

/* The startup banner: the usual copyright, expanded with build information.
 * COPYRIGHT_MESSAGE must be a string literal (basic.c concatenates it with
 * "\n\n"); the pieces below are joined at compile time. */
#define COPYRIGHT_MESSAGE \\
    "BerryBasiC (C) 2026 fritzone\\n" \\
    "v" BB_VERSION "  build " BB_BUILD_DATE "  (" BB_GIT_REV ")"

#endif /* CONF_H */
EOF

if [ -f "$OUT" ] && cmp -s "$TMP" "$OUT"; then
    rm -f "$TMP"                       # unchanged: leave mtime alone (no rebuild)
else
    mv "$TMP" "$OUT"
fi
