#!/usr/bin/env bash
#
# newseed.sh - scaffold a new BerryBasiC native seed from scratch.
#
# Creates a self-contained directory holding a starter source file and its own
# Makefile, so the seed builds into a loadable .sed blob with a plain 'make'.
#
#   tools/newseed.sh                 # prompt for the name
#   tools/newseed.sh blur            # name on the command line
#   tools/newseed.sh blur some/dir   # and an alternate parent directory
#
# (Or from the repo root:  make newseed NAME=blur)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SEED_API="$ROOT/seed"              # the seed API dir (seed.h, seed.ld, runtime/)
GARDEN="$SEED_API/garden"          # default home for hand-written seeds

# --- 1. get and validate the name ------------------------------------------
name="${1:-}"
if [ -z "$name" ]; then
    printf "Seed name: "
    read -r name
fi
name="$(printf '%s' "$name" | tr 'A-Z' 'a-z')"   # filenames stay lower case

if ! printf '%s' "$name" | grep -Eq '^[a-z][a-z0-9_]{0,7}$'; then
    echo "error: '$name' is not a valid seed name." >&2
    echo "  Use 1-8 characters: a lowercase letter first, then lowercase" >&2
    echo "  letters, digits or '_'. (The SD card uses FAT 8.3 names, and the" >&2
    echo "  name is also the C entry function, so it must be an identifier.)" >&2
    exit 1
fi

dest="${2:-$GARDEN}"
DIR="$dest/$name"
if [ -e "$DIR" ]; then
    echo "error: $DIR already exists - pick another name or remove it." >&2
    exit 1
fi

mkdir -p "$DIR"
REL_API="$(realpath --relative-to="$DIR" "$SEED_API")"   # seed dir -> seed API
UPPER="$(printf '%s' "$name" | tr 'a-z' 'A-Z')"
TAB="$(printf '\t')"

# --- 2. starter source ------------------------------------------------------
sed -e "s|@NAME@|$name|g" -e "s|@UPPER@|$UPPER|g" > "$DIR/$name.c" <<'EOF'
// @NAME@.sed - <describe what this seed does>
//
//   Build:  make                        (produces @NAME@.sed)
//   Load:   SEED h%, "@UPPER@.SED"
//   Call:   PRINT CALL(h%, ...)          numeric result
//           PRINT CALL$(h%, ...)         string result (via set_return_str)
//
// A seed must stay self-contained: work through argv, your own local helpers,
// the seed C library (<stdlib.h>/<string.h>/<ctype.h> - the OS-independent
// subset) and the svc services. Anything else (printf, file I/O, ...) fails to
// link. See the SeedServices vtable in seed.h for the full service API.
#include "seed.h"
#include <stdlib.h>
#include <string.h>

SEED_EXPORT(@NAME@)
{
    // svc  -> services back into the interpreter: printing, reading the
    //         keyboard, BASIC variables and arrays, alloc/free, set_return_str.
    // argv -> the CALL arguments; argv[i].is_str selects .num or .str/.len.
    // argc -> how many arguments were passed.
    (void)svc; (void)argv; (void)argc;

    // TODO: your work goes here.
    return 0;
}
EOF

# --- 3. per-seed Makefile ---------------------------------------------------
# Quoted heredoc keeps make's own $(...) literal; placeholders are filled by sed,
# and @TAB@ becomes a real tab so the recipe lines are valid.
sed -e "s|@REL_API@|$REL_API|g" -e "s|@NAME@|$name|g" -e "s|@UPPER@|$UPPER|g" \
    -e "s|@TAB@|$TAB|g" > "$DIR/Makefile" <<'EOF'
# Builds @NAME@.sed - a native BerryBasiC seed. Generated by tools/newseed.sh.
# Just run 'make'.  'make install' drops the blob into the repo's build/seeds/
# so the next 'make sdimage' at the repo root bundles it onto the card.

SEED     := @NAME@
SEED_API := @REL_API@

CROSS   ?= aarch64-linux-gnu-
CC      := $(CROSS)gcc
LD      := $(CROSS)ld
OBJCOPY := $(CROSS)objcopy
READELF := $(CROSS)readelf

# Same recipe as the main build: bare-metal, position-independent, no PIC/GOT.
# -I.../include = the seed C library (<stdlib.h>/<string.h>/<ctype.h>).
CFLAGS  := -O2 -ffreestanding -nostdlib -fno-builtin -mcpu=cortex-a72 -mstrict-align \
           -mcmodel=tiny -fno-pic -ffunction-sections -fdata-sections \
           -I$(SEED_API)/include -I$(SEED_API)

# The seed C library: every .c under seed/runtime/ is linked in; --gc-sections
# keeps only what this seed actually uses.
RT_SRC := $(wildcard $(SEED_API)/runtime/*.c)
RT_OBJ := $(patsubst $(SEED_API)/runtime/%.c,rt_%.o,$(RT_SRC))

all: $(SEED).sed

rt_%.o: $(SEED_API)/runtime/%.c
@TAB@$(CC) $(CFLAGS) -c $< -o $@

$(SEED).sed: $(SEED).c $(SEED_API)/seed.h $(SEED_API)/seed.ld $(RT_OBJ)
@TAB@$(CC) $(CFLAGS) -c $(SEED).c -o $(SEED).o
@TAB@$(LD) --gc-sections -T $(SEED_API)/seed.ld $(SEED).o $(RT_OBJ) -o $(SEED).elf
@TAB@@if $(READELF) -r $(SEED).elf | grep -q '^Relocation section'; then \
	    echo "SEED ERROR: $(SEED) is not self-contained (unresolved relocations):"; \
	    $(READELF) -r $(SEED).elf; rm -f $@; exit 1; fi
@TAB@$(OBJCOPY) -O binary $(SEED).elf $@
@TAB@@echo "  built $@  (load on the card as @UPPER@.SED)"

install: $(SEED).sed
@TAB@mkdir -p $(SEED_API)/../build/seeds
@TAB@cp $(SEED).sed $(SEED_API)/../build/seeds/$(SEED).sed
@TAB@@echo "  installed to build/seeds/$(SEED).sed"

clean:
@TAB@rm -f $(SEED).o rt_*.o $(SEED).elf $(SEED).sed

.PHONY: all install clean
EOF

rel="${DIR#$ROOT/}"
echo "Created seed '$name':"
echo "  source : $rel/$name.c"
echo "  build  : (cd $rel && make)        -> $name.sed"
echo "  bundle : (cd $rel && make install) then 'make sdimage' at the repo root"
