#ifndef BUILDCONFIG_H
#define BUILDCONFIG_H

// ---------------------------------------------------------------------------
// Build-time configuration: screen resolution and font.
// GENERATED by tools/configure.sh - re-run that script to change it.
// ---------------------------------------------------------------------------

// Native framebuffer resolution (pixels). boot/config.txt drives HDMI to match.
#define CFG_FB_WIDTH   1280
#define CFG_FB_HEIGHT  720

// Glyph cell (source pixels) and draw magnification. The font is ISO.F16.
#define CFG_GLYPH_W    8
#define CFG_GLYPH_H    16
#define CFG_FONT_SCALE 1

#endif
