#ifndef FONT_H
#define FONT_H

#include <stdint.h>
#include "buildconfig.h"

// The character set is GLYPH_W x GLYPH_H pixels. We render each glyph at an
// integer scale for a chunky, period-accurate look (FONT_SCALE=1 = raw font).
// Each glyph row is stored as one byte (MSB = leftmost pixel), so GLYPH_W must be
// <= 8; GLYPH_BYTES is the bytes per glyph and FONT_BYTES the whole table. The
// sizes come from buildconfig.h (generated by tools/configure.sh) - nothing else
// hard-codes the font dimensions.
#define GLYPH_W     CFG_GLYPH_W
#define GLYPH_H     CFG_GLYPH_H
#define GLYPH_BYTES (GLYPH_H)              // one byte per glyph row
#define FONT_GLYPHS 256                    // codes 0..255
#define FONT_BYTES  (FONT_GLYPHS * GLYPH_BYTES)
#define FONT_SCALE  CFG_FONT_SCALE
#define CHAR_W      (GLYPH_W * FONT_SCALE)
#define CHAR_H      (GLYPH_H * FONT_SCALE)

extern unsigned char bbc_font[FONT_BYTES]; // glyph table (mutable; VDU 23 edits it)

void draw_char(char c, int x, int y, uint32_t color);

#endif
