#include <stdint.h>
#include "uart.h"
#include "mailbox.h"
#include "graphics.h"
#include "font.h"
#include "usb_kbd.h"
#include "usb_hid.h"
#include "console.h"
#include "basic.h"
#include "mmu.h"
#include "sd.h"
#include "storage.h"
#include "pcie.h"
#include "xhci.h"

// ---------------------------------------------------------------------------
// Display configuration. The native resolution comes from src/buildconfig.h
// (generated by tools/configure.sh); a -DFB_WIDTH/-DFB_HEIGHT on the compiler
// command line still overrides it for one-off builds.
// ---------------------------------------------------------------------------
#include "buildconfig.h"
#ifndef FB_WIDTH
#define FB_WIDTH  CFG_FB_WIDTH
#endif
#ifndef FB_HEIGHT
#define FB_HEIGHT CFG_FB_HEIGHT
#endif

// CHAR_W / CHAR_H come from font.h (BBC 8x8 glyph scaled by FONT_SCALE).
#define TERM_COLS (FB_WIDTH  / CHAR_W)
#define TERM_ROWS (FB_HEIGHT / CHAR_H)

// Free-running 1 MHz system timer (low 32 bits); used to pace the cursor blink.
#define TIMER_CLO       (*(volatile uint32_t *)(0xFE003004UL))
#define CURSOR_BLINK_US 500000u   // half-period: on 500 ms, off 500 ms

static int cursor_col     = 0;
static int cursor_row     = 0;
static int fb_ready       = 0;
static uint32_t g_fb_phys = 0;   // framebuffer physical base (for non-cacheable remap)
static uint32_t g_fb_size = 0;   // framebuffer size in bytes
static int cursor_visible = 0;   // whether the cursor glyph is currently drawn
static uint32_t text_color = COLOR_WHITE;   // current foreground (BBC COLOUR)
static uint32_t text_bg    = COLOR_BLACK;   // current text background (VDU 17,128+c)

// VDU driver state.
static int vdu_enabled    = 1;   // VDU 6 / VDU 21: is screen output enabled?
static int vdu5_mode      = 0;   // VDU 5: write text at the graphics cursor
static int cursor_enabled = 1;   // VDU 23,1: is the text cursor (caret) shown?
// Text viewport, in character cells (inclusive). Default = whole screen.
static int tv_l = 0, tv_t = 0, tv_r = TERM_COLS - 1, tv_b = TERM_ROWS - 1;

// VDU 5 (text at the graphics cursor) helpers, defined with the graphics code
// further down but used by term_putchar above it.
static void gfx_text_char(unsigned char uc);   // draw a glyph at the gfx cursor, advance
static void gfx_text_cr(void);                 // carriage return (to viewport left)
static void gfx_text_lf(void);                 // line feed (down one char)
static void gfx_text_bs(void);                 // backspace (left one char)

// BBC logical colours 0..7 -> framebuffer RGBA (low byte = R, so 0xAABBGGRR).
// Mutable so VDU 19 can remap the palette; bbc_default_palette is the reset value
// for VDU 20 / MODE.
static const uint32_t bbc_default_palette[8] = {
    0xFF000000,  // 0 black
    0xFF0000FF,  // 1 red
    0xFF00FF00,  // 2 green
    0xFF00FFFF,  // 3 yellow
    0xFFFF0000,  // 4 blue
    0xFFFF00FF,  // 5 magenta
    0xFFFFFF00,  // 6 cyan
    0xFFFFFFFF,  // 7 white
};
static uint32_t bbc_palette[8] = {
    0xFF000000, 0xFF0000FF, 0xFF00FF00, 0xFF00FFFF,
    0xFFFF0000, 0xFFFF00FF, 0xFFFFFF00, 0xFFFFFFFF,
};
// Pack r,g,b (0..255) into a framebuffer pixel (RGB pixel order, red low byte).
static uint32_t rgb_pixel(int r, int g, int b) {
    return 0xFF000000u | ((uint32_t)(b & 0xff) << 16) |
           ((uint32_t)(g & 0xff) << 8) | (uint32_t)(r & 0xff);
}

// ---------------------------------------------------------------------------
// Terminal
// ---------------------------------------------------------------------------

// BBC-style flashing block cursor at the current cell. show=1 draws it, show=0
// erases it. The cursor always sits on the (empty) next-write cell, so erasing
// to black never clobbers a real glyph.
static void cursor_set(int show) {
    if (!fb_ready) return;
    if (show && !cursor_enabled) return;   // VDU 23,1,0 disables the caret
    int px = cursor_col * CHAR_W;
    int py = cursor_row * CHAR_H;
    bar(px, py, px + CHAR_W - 1, py + CHAR_H - 1,
        show ? COLOR_WHITE : COLOR_BLACK);
    cursor_visible = show;
}

// Newline: carriage-return to the viewport left, move down one row, scrolling the
// text viewport (which is the whole screen by default) when past the bottom.
static void term_advance(void) {
    cursor_col = tv_l;
    if (++cursor_row > tv_b) {
        scroll_rect(tv_l * CHAR_W, tv_t * CHAR_H,
                    (tv_r + 1) * CHAR_W - 1, (tv_b + 1) * CHAR_H - 1,
                    CHAR_H, text_bg);          // scroll one text row up
        cursor_row     = tv_b;                 // stay on the (new) bottom row
        cursor_visible = 0;                    // the scroll wiped any drawn cursor
    }
}

// Draw glyph `uc` (any code 0..255, so user-defined and VDU-27 chars work) at the
// cursor in the current colours, then advance. Caller must have lifted the cursor.
static void term_glyph(unsigned char uc) {
    int px = cursor_col * CHAR_W, py = cursor_row * CHAR_H;
    bar(px, py, px + CHAR_W - 1, py + CHAR_H - 1, text_bg);
    draw_char((char)uc, px, py, text_color);
    if (++cursor_col > tv_r) term_advance();
}

void term_putchar(char c) {
    if (!fb_ready) return;
    if (cursor_visible) cursor_set(0);   // lift cursor before editing the cell
    // VDU 5 mode: all character output (PRINT included) goes to the graphics
    // cursor instead of the text cursor.
    if (vdu5_mode) {
        if (c == '\r') { gfx_text_cr(); return; }
        if (c == '\n') { gfx_text_cr(); gfx_text_lf(); return; }   // PRINT newline = CR+LF
        if (c == '\b') { gfx_text_bs(); return; }
        if ((unsigned char)c < 32) return;
        gfx_text_char((unsigned char)c);
        return;
    }
    if (c == '\r') { cursor_col = tv_l; return; }
    if (c == '\n') { term_advance(); return; }
    if (c == '\t') {
        cursor_col = (cursor_col + 4) & ~3;
        if (cursor_col > tv_r) term_advance();
        return;
    }
    if (c == '\b') {
        if (cursor_col > tv_l) --cursor_col;
        else if (cursor_row > tv_t) { --cursor_row; cursor_col = tv_r; }
        else return;
        bar(cursor_col * CHAR_W, cursor_row * CHAR_H,
            cursor_col * CHAR_W + CHAR_W - 1, cursor_row * CHAR_H + CHAR_H - 1,
            text_bg);
        return;
    }
    if ((unsigned char)c < 32) return;   // other control codes: not printable here
    term_glyph((unsigned char)c);
}

static void term_puts(const char *s) {
    while (*s) term_putchar(*s++);
}

// ---------------------------------------------------------------------------
// Line editor
// ---------------------------------------------------------------------------

static int g_kbd_ok  = 0;   // DWC2 (USB-C) keyboard present
static int g_xhci_ok = 0;   // xHCI/VL805 (USB-A) keyboard present
static int g_sd_ready = 0;  // SD filesystem mounted (boot log can be written)

// Dump the in-RAM UART log to BOOTLOG.TXT on the SD card. Called at the end of
// boot (to diagnose USB enumeration) and from the exception handler (to surface
// a crash) on a board with no serial cable. Best-effort: needs the filesystem
// mounted, and guards against re-entry (e.g. an exception while already writing).
static void flush_boot_log(void) {
    static int busy = 0;
    if (!g_sd_ready || busy) return;
    busy = 1;
    const char *buf; int len;
    uart_log_get(&buf, &len);
    stg_write("BOOTLOG.TXT", buf, len);
    busy = 0;
}

// Emit a boot-progress line to *both* the UART/RAM log and, once it exists, the
// HDMI framebuffer. On a cableless board the screen is the only channel we know
// works (the firmware drew its own diagnostics on it), so mirroring boot stages
// there means the last line visible on screen is exactly where the kernel hung.
static void boot_msg(const char *s) {
    uart_puts(s);
    if (fb_ready) term_puts(s);
}

// Return the next input character from any keyboard (DWC2 USB-C or xHCI USB-A),
// falling back to the UART, or 0 if nothing is pending.
static char term_pollchar(void) {
    char c = 0;
    if (g_kbd_ok)  c = usb_kbd_getchar();
    if (!c && g_xhci_ok) c = xhci_kbd_getchar();
    if (!c)        c = uart_getc();
    return c;
}

// --- command-line history ---------------------------------------------------
#define HIST_MAX 16
#define HIST_LEN 256
static char hist_buf[HIST_MAX][HIST_LEN];
static int  hist_n = 0;      // entries stored (<= HIST_MAX)
static int  hist_head = 0;   // next slot to overwrite

static int kstrlen(const char *s) { int n = 0; while (s[n]) n++; return n; }
static void kstrcpy(char *d, const char *s, int max) {
    int i = 0; while (s[i] && i < max - 1) { d[i] = s[i]; i++; } d[i] = 0;
}
static int kstreq(const char *a, const char *b) {
    while (*a && *b) { if (*a != *b) return 0; a++; b++; } return *a == *b;
}
static void hist_push(const char *s) {
    if (!s[0]) return;
    if (hist_n && kstreq(hist_buf[(hist_head - 1 + HIST_MAX) % HIST_MAX], s)) return;
    kstrcpy(hist_buf[hist_head], s, HIST_LEN);
    hist_head = (hist_head + 1) % HIST_MAX;
    if (hist_n < HIST_MAX) hist_n++;
}
static const char *hist_get(int age) {           // age 1 = most recent
    if (age < 1 || age > hist_n) return 0;
    return hist_buf[(hist_head - age + HIST_MAX) % HIST_MAX];
}

// Poll for one input byte for up to `ms` milliseconds (used to read the rest of
// a terminal escape sequence). 0 = nothing arrived.
static char poll_byte_ms(int ms) {
    uint32_t t0 = TIMER_CLO;
    for (;;) {
        char c = term_pollchar();
        if (c) return c;
        if (TIMER_CLO - t0 >= (uint32_t)ms * 1000) return 0;
    }
}

// Map a terminal CSI escape sequence (after ESC) to an editing key, for serial
// use. The HID keyboard delivers KEY_* codes directly.
static char read_esc_seq(void) {
    if (poll_byte_ms(20) != '[') return 0;
    char b = poll_byte_ms(20);
    switch (b) {
        case 'A': return KEY_UP;
        case 'B': return KEY_DOWN;
        case 'C': return KEY_RIGHT;
        case 'D': return KEY_LEFT;
        case 'H': return KEY_HOME;
        case 'F': return KEY_END;
        case '3': poll_byte_ms(20); return KEY_DEL;   // ESC [ 3 ~
        default:  return 0;
    }
}

// Position the framebuffer cursor at editable offset `off` from start (sc,sr).
static void edit_cursor_at(int sc, int sr, int off) {
    int t = sc + off;
    cursor_col = t % TERM_COLS;
    cursor_row = sr + t / TERM_COLS;
    if (cursor_row >= TERM_ROWS) cursor_row = TERM_ROWS - 1;
}

// Redraw the editable region (screen + serial) and place the cursor at `pos`.
static void edit_render(int sc, int sr, const char *prompt,
                        const char *buf, int len, int pos, int prev_len) {
    if (fb_ready) {
        if (cursor_visible) cursor_set(0);
        cursor_col = sc; cursor_row = sr;
        for (int i = 0; i < len; i++) term_putchar(buf[i]);
        for (int i = len; i < prev_len; i++) term_putchar(' ');   // erase leftovers
        edit_cursor_at(sc, sr, pos);
    }
    uart_putc('\r'); uart_puts(prompt);
    for (int i = 0; i < len; i++) uart_putc(buf[i]);
    uart_puts("\033[K");                              // clear to end of line
    for (int i = pos; i < len; i++) uart_putc('\b');  // back to the cursor column
}

// Full line editor: prints `prompt`, starts with `prefill_len` editable chars in
// buf, supports cursor movement (Left/Right/Home/End), insert/backspace/delete,
// and Up/Down command history. Returns the final length.
int term_getline_ed(char *buf, int maxlen, int prefill_len, const char *prompt) {
    int len = prefill_len;
    if (len > maxlen - 1) len = maxlen - 1;
    buf[len] = 0;
    int pos = len;

    if (fb_ready) { if (cursor_visible) cursor_set(0); for (const char *p = prompt; *p; p++) term_putchar(*p); }
    int sc = cursor_col, sr = cursor_row;
    int prev_len = 0;
    edit_render(sc, sr, prompt, buf, len, pos, prev_len);
    prev_len = len;

    int hist_age = 0;                 // 0 = editing current; >0 = browsing history
    char saved[HIST_LEN]; saved[0] = 0;
    uint32_t last_blink = TIMER_CLO;

    for (;;) {
        char c = term_pollchar();
        if (c == 0x1B) c = read_esc_seq();       // serial arrow keys (ESC [ ...)
        if (!c) {
            uint32_t now = TIMER_CLO;
            if (now - last_blink >= CURSOR_BLINK_US) {
                last_blink = now;
                edit_cursor_at(sc, sr, pos);
                cursor_set(!cursor_visible);
            }
            continue;
        }

        if (c == '\r' || c == '\n') {
            if (fb_ready) { if (cursor_visible) cursor_set(0); edit_cursor_at(sc, sr, len); term_putchar('\n'); }
            uart_puts("\r\n");
            buf[len] = 0;
            hist_push(buf);
            return len;
        }
        if (c == '\b') {                          // backspace (delete left of cursor)
            if (pos > 0) {
                for (int i = pos - 1; i < len - 1; i++) buf[i] = buf[i + 1];
                len--; pos--; buf[len] = 0;
            }
        } else if (c == KEY_DEL) {                // forward delete
            if (pos < len) {
                for (int i = pos; i < len - 1; i++) buf[i] = buf[i + 1];
                len--; buf[len] = 0;
            }
        } else if (c == KEY_LEFT)  { if (pos > 0)   pos--; }
        else if (c == KEY_RIGHT) { if (pos < len) pos++; }
        else if (c == KEY_HOME)  { pos = 0; }
        else if (c == KEY_END)   { pos = len; }
        else if (c == KEY_UP) {
            if (hist_age < hist_n) {
                if (hist_age == 0) kstrcpy(saved, buf, HIST_LEN);
                kstrcpy(buf, hist_get(++hist_age), maxlen);
                len = kstrlen(buf); pos = len;
            }
        } else if (c == KEY_DOWN) {
            if (hist_age > 0) {
                hist_age--;
                kstrcpy(buf, hist_age == 0 ? saved : hist_get(hist_age), maxlen);
                len = kstrlen(buf); pos = len;
            }
        } else if (c >= 32 && c <= 126) {         // insert a printable char at cursor
            if (len < maxlen - 1) {
                for (int i = len; i > pos; i--) buf[i] = buf[i - 1];
                buf[pos++] = c; len++; buf[len] = 0;
            }
        } else {
            continue;                              // ignore other control codes
        }

        edit_render(sc, sr, prompt, buf, len, pos, prev_len);
        prev_len = len;
        last_blink = TIMER_CLO;
    }
}

int term_getline(char *buf, int maxlen) {
    return term_getline_ed(buf, maxlen, 0, "");
}

// ---------------------------------------------------------------------------
// Console backend for the BASIC interpreter (console.h). Output is mirrored to
// both the framebuffer terminal and the UART so headless/serial use works too.
// ---------------------------------------------------------------------------

void con_putc(char c) {
    if (c == '\n') { term_putchar('\n'); uart_puts("\r\n"); }
    else           { term_putchar(c);    uart_putc(c); }
}

void con_puts(const char *s) {
    while (*s) con_putc(*s++);
}

int con_getline(char *buf, int maxlen) {
    return term_getline(buf, maxlen);   // never EOFs on the target
}

int con_getline_ed(char *buf, int maxlen, int prefill_len, const char *prompt) {
    return term_getline_ed(buf, maxlen, prefill_len, prompt);
}

void con_cls(void) {
    if (fb_ready) {
        if (cursor_visible) cursor_set(0);
        // Clear the text viewport (the whole screen by default) to the text
        // background colour.
        fill_rect(tv_l * CHAR_W, tv_t * CHAR_H,
                  (tv_r + 1) * CHAR_W - 1, (tv_b + 1) * CHAR_H - 1, text_bg);
    }
    cursor_col = tv_l;
    cursor_row = tv_t;
    cursor_visible = 0;
    uart_puts("\r\n");
}

void con_colour(int c) {
    if (c >= 128) text_bg    = bbc_palette[(c - 128) & 7];   // COLOUR 128+c: background
    else          text_color = bbc_palette[c & 7];           // COLOUR c: foreground
}

// Block until a key is pressed; return its ASCII code (BBC GET).
int con_getkey(void) {
    uint32_t last_blink = TIMER_CLO;
    for (;;) {
        char c = term_pollchar();
        if (c) { if (cursor_visible) cursor_set(0); return (unsigned char)c; }
        uint32_t now = TIMER_CLO;
        if (now - last_blink >= CURSOR_BLINK_US) {
            last_blink = now;
            cursor_set(!cursor_visible);
        }
    }
}

#define TIMER_CHI (*(volatile uint32_t *)(0xFE003008UL))

unsigned long long con_micros(void) {
    uint32_t hi, lo;
    do { hi = TIMER_CHI; lo = TIMER_CLO; } while (hi != TIMER_CHI);  // guard wrap
    return ((unsigned long long)hi << 32) | lo;
}

// Wait up to `centiseconds` (1/100 s) for a key; return its code or -1.
int con_inkey(int centiseconds) {
    uint32_t t0 = TIMER_CLO;
    uint32_t limit = (centiseconds > 0) ? (uint32_t)centiseconds * 10000u : 0;
    uint32_t last_blink = TIMER_CLO;
    for (;;) {
        char c = term_pollchar();
        if (c) { if (cursor_visible) cursor_set(0); return (unsigned char)c; }
        if (TIMER_CLO - t0 >= limit) return -1;
        uint32_t now = TIMER_CLO;
        if (now - last_blink >= CURSOR_BLINK_US) {
            last_blink = now;
            cursor_set(!cursor_visible);
        }
    }
}

int con_pos(void)  { return cursor_col; }
int con_vpos(void) { return cursor_row; }

// ---------------------------------------------------------------------------
// Boot logo (embedded RGB image from logo_data.c)
// ---------------------------------------------------------------------------

extern const unsigned int  logo_w;
extern const unsigned int  logo_h;
extern const unsigned char logo_rgb[];

static int g_show_logo = 0;   // set at boot once the framebuffer is up

// Draw the embedded RGB logo at framebuffer pixel (ox, oy), shrunk by integer
// factor `div` (nearest-neighbour). Colours are already baked into logo_rgb
// (black background, green leaves, raspberry-red berry). The framebuffer is
// RGBA byte-order (low byte = R), so a pixel is 0xFF000000 | B<<16 | G<<8 | R.
static void draw_logo(int ox, int oy, int div) {
    unsigned int dw = logo_w / div, dh = logo_h / div;
    for (unsigned int y = 0; y < dh; y++) {
        for (unsigned int x = 0; x < dw; x++) {
            const unsigned char *p = logo_rgb + ((y * div) * logo_w + (x * div)) * 3;
            uint32_t r = p[0], g = p[1], b = p[2];
            putpixel(ox + (int)x, oy + (int)y,
                     0xFF000000u | (b << 16) | (g << 8) | r);
        }
    }
}

// Show the boot splash. On the target this clears the boot-progress text, paints
// the logo on the left, prints the banner beside it (vertically centred on the
// logo), parks the text cursor cleanly below the logo, and returns 1 so the
// caller does not print the banner again. Returns 0 when no logo is shown (e.g.
// the host build), in which case the caller prints the banner itself.
int con_splash(const char *banner) {
    if (!g_show_logo || !fb_ready) return 0;
    cleardevice();                                    // wipe the boot-progress text
    int div = 2;                                      // half size
    int lw = (int)logo_w / div, lh = (int)logo_h / div;
    int ox = CHAR_W;                                  // small left margin
    int oy = CHAR_H;                                  // small top margin
    draw_logo(ox, oy, div);                           // left side, half size

    // Banner beside the logo, vertically centred on it.
    cursor_col = (ox + lw) / CHAR_W + 1;
    cursor_row = (oy + lh / 2) / CHAR_H;
    cursor_visible = 0;
    con_puts(banner);
    uart_puts("\r\n");                                // tidy the serial line

    // Park the cursor below the logo for the REPL prompt.
    cursor_col = 0;
    cursor_row = (oy + lh) / CHAR_H + 1;
    cursor_visible = 0;
    return 1;
}

// ---------------------------------------------------------------------------
// BBC-style graphics
//
// Logical coordinate space is 1280x1024 with the origin at the bottom-left,
// mapped onto the physical framebuffer. State: graphics foreground/background
// colours, the GCOL plot action, and a short history of the last three points
// (PLOT lines use the last two, triangles the last three, circles use the last
// two as centre + a point on the circumference).
// ---------------------------------------------------------------------------

#define GFX_LW 1280
#define GFX_LH 1024

static int gfx_fg  = 7;     // graphics foreground (logical colour)
static int gfx_bg  = 0;     // graphics background
static int gfx_act = 0;     // GCOL plot action (0=store 1=OR 2=AND 3=EOR 4=invert)
static int gpx0, gpy0;      // most recent point (logical, origin-relative)
static int gpx1, gpy1;      // previous point
static int gpx2, gpy2;      // the one before that
static int gfx_ox = 0, gfx_oy = 0;   // graphics origin (VDU 29 / ORIGIN)

static int lx2px(int x) { return (x + gfx_ox) * FB_WIDTH  / GFX_LW; }
static int ly2py(int y) { return (FB_HEIGHT - 1) - ((y + gfx_oy) * FB_HEIGHT / GFX_LH); }
// Inverse transforms (physical pixel -> logical, origin-relative).
static int px2lx(int px) { return px * GFX_LW / FB_WIDTH - gfx_ox; }
static int py2ly(int py) { return (FB_HEIGHT - 1 - py) * GFX_LH / FB_HEIGHT - gfx_oy; }

static int isqrt_i(int v) {
    if (v <= 0) return 0;
    int r = 0;
    while ((r + 1) * (r + 1) <= v) r++;
    return r;
}

// Reset the default text/graphics viewports and graphics origin (VDU 26).
static void reset_viewports(void) {
    tv_l = 0; tv_t = 0; tv_r = TERM_COLS - 1; tv_b = TERM_ROWS - 1;
    gfx_clear_clip();
    gfx_ox = 0; gfx_oy = 0;
    gpx0 = gpy0 = gpx1 = gpy1 = gpx2 = gpy2 = 0;
}

// Restore the default logical colours and palette (VDU 20).
static void reset_colours(void) {
    for (int i = 0; i < 8; i++) bbc_palette[i] = bbc_default_palette[i];
    text_color = bbc_palette[7];     // COLOUR 7
    text_bg    = bbc_palette[0];     // COLOUR 128
    gfx_fg = 7; gfx_bg = 0; gfx_act = 0;
    gfx_set_op(0);
}

void con_mode(int n) {
    (void)n;                                  // resolution is fixed; MODE just resets
    reset_colours();
    reset_viewports();
    vdu5_mode = 0; vdu_enabled = 1; cursor_enabled = 1;
    if (fb_ready) cleardevice();
    cursor_col = 0; cursor_row = 0; cursor_visible = 0;
    uart_puts("\r\n");
}

void con_gcol(int action, int colour) {
    gfx_act = action & 7;
    if (colour >= 128) gfx_bg = (colour - 128) & 7;   // GCOL a,128+c sets background
    else               gfx_fg = colour & 7;
}

void con_clg(void) {
    if (!fb_ready) return;
    int x0, y0, x1, y1;
    gfx_clip_rect(&x0, &y0, &x1, &y1);         // clear only the graphics viewport
    gfx_set_op(0);
    fill_rect(x0, y0, x1, y1, bbc_palette[gfx_bg & 7]);
}

void con_plot(int code, int x, int y) {
    if (!fb_ready) return;
    int absolute = code & 4;
    int cmode    = code & 3;        // 0=move 1=foreground 2=inverse 3=background
    int group    = code & 0xF8;

    int nx, ny;
    if (absolute) { nx = x;        ny = y;        }
    else          { nx = gpx0 + x; ny = gpy0 + y; }

    gpx2 = gpx1; gpy2 = gpy1;       // shift point history
    gpx1 = gpx0; gpy1 = gpy0;
    gpx0 = nx;   gpy0 = ny;

    if (group == 0 && cmode == 0) return;          // plain MOVE

    uint32_t col = (cmode == 3) ? bbc_palette[gfx_bg & 7] : bbc_palette[gfx_fg & 7];
    int op = (cmode == 2) ? 3 : gfx_act;           // inverse colour -> EOR
    gfx_set_op(op);

    int x0 = lx2px(gpx0), y0 = ly2py(gpy0);
    int x1 = lx2px(gpx1), y1 = ly2py(gpy1);
    int x2 = lx2px(gpx2), y2 = ly2py(gpy2);

    switch (group) {
        case 0:    draw_line(x1, y1, x0, y0, col); break;          // line
        case 64:   draw_line(x0, y0, x0, y0, col); break;          // single point
        case 80:   fill_triangle(x0, y0, x1, y1, x2, y2, col); break;   // triangle
        case 96:   fill_rect(x1, y1, x0, y0, col); break;          // rectangle
        case 144:                                                   // circle outline
        case 152: {                                                 // circle fill
            int dx = x0 - x1, dy = y0 - y1;
            int r  = isqrt_i(dx * dx + dy * dy);
            if (group == 152) fill_circle(x1, y1, r, col);
            else              draw_circle(x1, y1, r, col);
            break;
        }
        default:   draw_line(x1, y1, x0, y0, col); break;          // fallback: line
    }
    gfx_set_op(0);                                  // leave op at store
}

int con_point(int x, int y) {
    if (!fb_ready) return -1;
    if (x < 0 || x >= GFX_LW || y < 0 || y >= GFX_LH) return -1;
    uint32_t px = getpixel(lx2px(x), ly2py(y));
    for (int i = 0; i < 8; i++) if (bbc_palette[i] == px) return i;
    return -1;
}

// ---------------------------------------------------------------------------
// VDU driver - interprets a byte stream as the BBC Micro's VDU does. The BASIC
// VDU statement feeds each byte here; control codes 0..31 (and 127) act on the
// screen, consuming a fixed number of following parameter bytes; codes >= 32 are
// printable characters. See the VDU code summary for what each does.
// ---------------------------------------------------------------------------

// Parameter bytes consumed by each control code 0..31.
static const unsigned char vdu_nparams[32] = {
    0,1,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,
    0,1,2,5,0,0,1,9, 8,5,0,1,4,4,0,2
};
static uint8_t vdu_q[16];
static int vdu_qn = 0, vdu_qneed = 0, vdu_cmd = -1;

static int vdu_word(int i)  { return vdu_q[i] | (vdu_q[i+1] << 8); }
static int vdu_sword(int i) { int v = vdu_word(i); return v >= 32768 ? v - 65536 : v; }
static int gfx_char_w(void) { return CHAR_W * GFX_LW / FB_WIDTH; }
static int gfx_char_h(void) { return CHAR_H * GFX_LH / FB_HEIGHT; }
static int clampi(int v, int lo, int hi) { return v < lo ? lo : v > hi ? hi : v; }

// --- VDU 5: text at the graphics cursor -------------------------------------
// Logical coordinates of the left and top edges of the graphics viewport (the
// whole screen unless VDU 24 set one), used as the "home" / line-start position.
static int gfx_vp_left(void) { int x0,y0,x1,y1; gfx_clip_rect(&x0,&y0,&x1,&y1); return px2lx(x0); }
static int gfx_vp_top(void)  { int x0,y0,x1,y1; gfx_clip_rect(&x0,&y0,&x1,&y1); return py2ly(y0); }

// Draw one glyph at the graphics cursor: the cursor is the TOP-LEFT of the cell,
// plotted in the graphics foreground colour using the current GCOL plot action,
// with a transparent background, clipped to the graphics viewport. Then advance
// the graphics cursor right by one character width.
static void gfx_text_char(unsigned char uc) {
    gfx_set_op(gfx_act);
    draw_glyph_op(&bbc_font[uc * GLYPH_BYTES], lx2px(gpx0), ly2py(gpy0), FONT_SCALE,
                  bbc_palette[gfx_fg & 7]);
    gfx_set_op(0);
    gpx0 += gfx_char_w();
}
static void gfx_text_cr(void) { gpx0 = gfx_vp_left(); }
static void gfx_text_lf(void) { gpy0 -= gfx_char_h(); }
static void gfx_text_bs(void) { gpx0 -= gfx_char_w(); }

// Output a printable character: at the graphics cursor in VDU 5 mode, otherwise
// at the text cursor (mirrored to serial like PRINT).
static void vdu_putchar(int uc) {
    if (cursor_visible) cursor_set(0);
    if (vdu5_mode) gfx_text_char((unsigned char)uc);
    else           term_glyph((unsigned char)uc);
    // VDU-statement characters don't pass through con_putc, so mirror them to the
    // serial console here (PRINT-driven characters are mirrored by con_putc).
    if (uc >= 32 && uc < 127) uart_putc((char)uc);
}

static void vdu_del(void) {
    if (!fb_ready) return;
    if (cursor_visible) cursor_set(0);
    if (vdu5_mode) {                          // VDU 5: backspace + erase at gfx cursor
        gpx0 -= gfx_char_w();                 // ... using the graphics background colour
        int px = lx2px(gpx0), py = ly2py(gpy0);
        gfx_set_op(0);
        fill_rect(px, py, px + CHAR_W - 1, py + CHAR_H - 1, bbc_palette[gfx_bg & 7]);
        return;
    }
    if (cursor_col > tv_l) --cursor_col;
    else if (cursor_row > tv_t) { --cursor_row; cursor_col = tv_r; }
    else return;
    bar(cursor_col * CHAR_W, cursor_row * CHAR_H,
        cursor_col * CHAR_W + CHAR_W - 1, cursor_row * CHAR_H + CHAR_H - 1, text_bg);
}

static void vdu_execute(int cmd) {
    // When output is disabled (VDU 21) only VDU 6 (re-enable) is acted upon.
    if (!vdu_enabled && cmd != 6) return;
    if (cursor_visible && cmd < 32) cursor_set(0);

    switch (cmd) {
        case 0:  break;                                   // null
        case 1:  break;                                   // -> printer only (no printer)
        case 2:  case 3: break;                           // printer enable/disable (none)
        case 4:  vdu5_mode = 0; break;                    // text at text cursor
        case 5:  vdu5_mode = 1; break;                    // text at graphics cursor
        case 6:  vdu_enabled = 1; break;                  // enable screen output
        case 7:  break;                                   // bell (no audio)
        case 8:  if (vdu5_mode) gpx0 -= gfx_char_w();      // cursor left
                 else if (cursor_col > tv_l) cursor_col--;
                 else if (cursor_row > tv_t) { cursor_row--; cursor_col = tv_r; }
                 break;
        case 9:  if (vdu5_mode) gpx0 += gfx_char_w();      // cursor right
                 else if (cursor_col < tv_r) cursor_col++;
                 else term_advance();
                 break;
        case 10: if (vdu5_mode) gpy0 -= gfx_char_h();      // cursor down (LF)
                 else { if (++cursor_row > tv_b) { scroll_rect(tv_l*CHAR_W, tv_t*CHAR_H,
                            (tv_r+1)*CHAR_W-1, (tv_b+1)*CHAR_H-1, CHAR_H, text_bg);
                            cursor_row = tv_b; } }
                 break;
        case 11: if (vdu5_mode) gpy0 += gfx_char_h();      // cursor up
                 else if (cursor_row > tv_t) cursor_row--;
                 break;
        case 12: con_cls(); break;                         // clear text (CLS)
        case 13: if (vdu5_mode) gfx_text_cr();             // carriage return
                 else cursor_col = tv_l;
                 break;
        case 14: case 15: break;                           // auto-paging (not implemented)
        case 16: con_clg(); break;                         // clear graphics (CLG)
        case 17: con_colour(vdu_q[0]); break;              // COLOUR
        case 18: con_gcol(vdu_q[0], vdu_q[1]); break;      // GCOL
        case 19: {                                         // palette
            int l = vdu_q[0] & 7, p = vdu_q[1];
            if (p == 16)       bbc_palette[l] = rgb_pixel(vdu_q[2], vdu_q[3], vdu_q[4]);
            else if (p == 255) bbc_palette[l] = rgb_pixel(vdu_q[2]*4, vdu_q[3]*4, vdu_q[4]*4);
            else               bbc_palette[l] = bbc_default_palette[p & 7];
            break;
        }
        case 20: reset_colours(); break;                   // default colours + palette
        case 21: vdu_enabled = 0; break;                   // disable screen output
        case 22: con_mode(vdu_q[0]); break;                // MODE
        case 23: {                                         // user-defined char / control
            int sub = vdu_q[0];
            if (sub >= 32) {                               // redefine character `sub`
                // VDU 23 always carries 8 row bytes (r1..r8); copy as many as the
                // glyph holds (GLYPH_BYTES rows).
                for (int i = 0; i < 8 && i < GLYPH_BYTES; i++)
                    bbc_font[sub * GLYPH_BYTES + i] = vdu_q[1 + i];
            } else if (sub == 1) {                         // text cursor (caret) on/off
                cursor_enabled = (vdu_q[1] != 0);
                if (!cursor_enabled && cursor_visible) cursor_set(0);
            } else if (sub == 7) {                         // scroll the text viewport
                int d = vdu_q[2];                          // 0=right 1=left 2=down 3=up
                int dx = (d == 0) ? CHAR_W : (d == 1) ? -CHAR_W : 0;
                int dy = (d == 2) ? CHAR_H : (d == 3) ? -CHAR_H : 0;
                move_rect(tv_l * CHAR_W, tv_t * CHAR_H,
                          (tv_r + 1) * CHAR_W - 1, (tv_b + 1) * CHAR_H - 1,
                          dx, dy, text_bg);
            }
            // sub 0 (cursor appearance), 16 (cursor-movement flags), 18 (MODE 7),
            // 22 (user-defined screen modes) and 23 (line thickness) are parsed
            // but not implemented - they don't map to this fixed-mode display.
            break;
        }
        case 24:                                            // graphics viewport
            gfx_set_clip(lx2px(vdu_sword(0)), ly2py(vdu_sword(6)),
                         lx2px(vdu_sword(4)), ly2py(vdu_sword(2)));
            break;
        case 25: con_plot(vdu_q[0], vdu_sword(1), vdu_sword(3)); break;   // PLOT
        case 26: reset_viewports(); cursor_col = tv_l; cursor_row = tv_t; break;
        case 27: vdu_putchar(vdu_q[0]); break;             // print next byte literally
        case 28: {                                          // text viewport
            int l = clampi(vdu_q[0],0,TERM_COLS-1), bm = clampi(vdu_q[1],0,TERM_ROWS-1);
            int r = clampi(vdu_q[2],0,TERM_COLS-1), t  = clampi(vdu_q[3],0,TERM_ROWS-1);
            tv_l = l < r ? l : r; tv_r = l < r ? r : l;
            tv_t = t < bm ? t : bm; tv_b = t < bm ? bm : t;
            cursor_col = tv_l; cursor_row = tv_t;
            break;
        }
        case 29: gfx_ox = vdu_sword(0); gfx_oy = vdu_sword(2); break;   // ORIGIN
        case 30: if (vdu5_mode) { gpx0 = gfx_vp_left(); gpy0 = gfx_vp_top(); }  // home
                 else { cursor_col = tv_l; cursor_row = tv_t; }
                 break;
        case 31: cursor_col = clampi(tv_l + vdu_q[0], tv_l, tv_r);     // TAB(x,y)
                 cursor_row = clampi(tv_t + vdu_q[1], tv_t, tv_b);
                 break;
        default: break;
    }
}

void con_vdu(int b) {
    b &= 0xff;
    if (vdu_cmd >= 0) {                       // collecting parameter bytes
        vdu_q[vdu_qn++] = (uint8_t)b;
        if (vdu_qn < vdu_qneed) return;
        int cmd = vdu_cmd; vdu_cmd = -1;
        vdu_execute(cmd);
        return;
    }
    if (b < 32) {
        int need = vdu_nparams[b];
        if (need) { vdu_cmd = b; vdu_qn = 0; vdu_qneed = need; return; }
        vdu_execute(b);                       // zero-parameter control code
        return;
    }
    if (b == 127) { if (vdu_enabled) vdu_del(); return; }
    if (vdu_enabled) vdu_putchar(b);          // printable character
}

// ---------------------------------------------------------------------------
// Exception handler (called from the vector table in vectors.S)
// ---------------------------------------------------------------------------

// Print a labelled hex value straight to the framebuffer terminal (used by the
// exception handler so fault details are readable on screen even when the SD
// log write itself fails).
static void term_hexval(const char *label, uint64_t v, int digits) {
    term_puts(label);
    const char *h = "0123456789ABCDEF";
    for (int i = (digits - 1) * 4; i >= 0; i -= 4)
        term_putchar(h[(v >> i) & 0xF]);
    term_putchar('\n');
}

// Print the last `max_lines` lines of the in-RAM boot log to the framebuffer.
// Lets the exception handler show how far boot got (e.g. the [PCIE]/[XHCI]
// progress lines) on screen, without needing the SD card.
static void term_log_tail(int max_lines) {
    const char *buf; int len;
    uart_log_get(&buf, &len);
    int start = 0, nl = 0;
    for (int i = len - 1; i >= 0; i--) {
        if (buf[i] == '\n') { if (++nl > max_lines) { start = i + 1; break; } }
    }
    for (int i = start; i < len; i++) term_putchar(buf[i]);
}

void exception_handler(uint64_t type, uint64_t esr, uint64_t elr, uint64_t far) {
    static const char *vec_names[16] = {
        "SYNC/SP0",  "IRQ/SP0",  "FIQ/SP0",  "SERROR/SP0",
        "SYNC",      "IRQ",      "FIQ",       "SERROR",
        "SYNC/L64",  "IRQ/L64",  "FIQ/L64",   "SERROR/L64",
        "SYNC/L32",  "IRQ/L32",  "FIQ/L32",   "SERROR/L32",
    };
    uint32_t ec = (uint32_t)(esr >> 26) & 0x3F;
    const char *cause = "unknown";
    switch (ec) {
        case 0x00: cause = "unknown reason";       break;
        case 0x20: case 0x21: cause = "instruction abort"; break;
        case 0x22: cause = "PC alignment fault";   break;
        case 0x24: case 0x25: cause = "data abort"; break;
        case 0x26: cause = "SP alignment fault";   break;
        case 0x3C: cause = "BRK instruction";      break;
    }

    uart_puts("\n\n*** UNHANDLED EXCEPTION ***\n");
    uart_puts("vector : "); uart_puts(vec_names[type & 15]); uart_putc('\n');
    uart_puts("cause  : "); uart_puts(cause);                uart_putc('\n');
    uart_hex  ("ESR_EL1: ", (uint32_t)esr);
    uart_hex  ("  EC   : ", ec);
    uart_hex64("ELR_EL1: ", elr);   // faulting instruction
    uart_hex64("FAR_EL1: ", far);   // faulting address
    uart_puts("system halted.\n");

    // Paint the fault details straight onto the screen FIRST - this is just
    // framebuffer memory writes, so it works even when the SD/FAT path that
    // flush_boot_log() uses is itself wedged by the fault (e.g. a pending PCIe
    // SError that re-fires during the SD write). Read these off the screen.
    if (fb_ready) {
        fill_rect(0, 0, FB_WIDTH - 1, FB_HEIGHT - 1, COLOR_BLACK);
        cursor_col = 0; cursor_row = 0; cursor_visible = 0;
        text_color = COLOR_WHITE;
        // Recent boot progress first (shows the [PCIE]/[XHCI] lines), then the
        // fault details at the bottom so they stay visible if the log scrolls.
        term_puts("--- recent log ---\n");
        term_log_tail(20);
        term_puts("*** EXCEPTION ***\n");
        term_puts("vector: "); term_puts(vec_names[type & 15]); term_putchar('\n');
        term_puts("cause : "); term_puts(cause); term_putchar('\n');
        term_hexval("ESR = ", esr, 8);
        term_hexval("ELR = ", elr, 16);
        term_hexval("FAR = ", far, 16);
    }

    // Then also try to dump the full log to the SD card (best-effort).
    flush_boot_log();
    // vectors.S halts the CPU after we return.
}

// ---------------------------------------------------------------------------
// Board identification
// ---------------------------------------------------------------------------

// Query and log the board serial (tag 0x00010004). Real Pi hardware returns a
// nonzero serial; QEMU's raspi4b leaves it 0. Returns 1 on real hardware. We use
// this to avoid touching the PCIe controller under QEMU, which does not model it
// (an access there raises an external abort).
static int board_real_hw(void) {
    mbox[0] = 9 * 4;
    mbox[1] = 0;
    mbox[2] = 0x00010004; mbox[3] = 8; mbox[4] = 0;   // get board serial
    mbox[5] = 0; mbox[6] = 0;
    mbox[7] = 0;                                       // end tag
    mbox[8] = 0;
    mbox_call();
    uart_hex("[BOARD] serial lo: ", mbox[5]);
    uart_hex("[BOARD] serial hi: ", mbox[6]);
    return (mbox[5] | mbox[6]) != 0;
}

// ---------------------------------------------------------------------------
// Framebuffer setup via mailbox
// ---------------------------------------------------------------------------

static int setup_fb(void) {
    mbox[ 0] = 35 * 4;
    mbox[ 1] = 0;
    mbox[ 2] = 0x00048003; mbox[ 3] = 8; mbox[ 4] = 8;   // set physical w/h
    mbox[ 5] = FB_WIDTH;
    mbox[ 6] = FB_HEIGHT;
    mbox[ 7] = 0x00048004; mbox[ 8] = 8; mbox[ 9] = 8;   // set virtual w/h
    mbox[10] = FB_WIDTH;
    mbox[11] = FB_HEIGHT;
    mbox[12] = 0x00048005; mbox[13] = 4; mbox[14] = 4;   // set depth
    mbox[15] = 32;
    // Force pixel order to RGB (1). Without this each platform uses its own
    // default - QEMU is RGB but the real Pi 4 firmware defaults to BGR, which
    // swaps red/blue and turns the raspberry logo purple. We pack pixels with red
    // in the low byte, which is the RGB order.
    mbox[16] = 0x00048006; mbox[17] = 4; mbox[18] = 4;   // set pixel order
    mbox[19] = 1;                                        // 1 = RGB
    mbox[20] = 0x00040001; mbox[21] = 8; mbox[22] = 8;   // allocate framebuffer
    mbox[23] = 4096;                                     // -> base address
    mbox[24] = 0;                                        // -> size
    mbox[25] = 0x00040008; mbox[26] = 4; mbox[27] = 4;   // get pitch
    mbox[28] = 0;                                        // -> pitch
    mbox[29] = 0;                                        // end tag

    int ok = mbox_call();
    uart_dec("[FB] mbox_call returned: ", (uint32_t)ok);
    uart_hex("[FB] mbox[1] response:   ", mbox[1]);
    uart_dec("[FB] width:  ", mbox[5]);
    uart_dec("[FB] height: ", mbox[6]);
    uart_hex("[FB] pixel order: ", mbox[19]);
    uart_hex("[FB] bus addr: ", mbox[23]);
    uart_dec("[FB] size:   ", mbox[24]);
    uart_dec("[FB] pitch:  ", mbox[28]);

    if (!ok || mbox[28] == 0) return 0;

    uint32_t fb_bus  = mbox[23];
    uint32_t fb_phys = fb_bus & 0x3FFFFFFF;  // strip VideoCore bus alias
    uint32_t pitch   = mbox[28];
    uint32_t fb_size = mbox[24];
    uint32_t *fb     = (uint32_t *)(uintptr_t)fb_phys;

    uart_hex("[FB] physical: ", fb_phys);
    // The framebuffer is brought up before the MMU (see kernel_main), so we just
    // record its extent here; kernel_main re-marks it non-cacheable once the MMU
    // page tables exist, so CPU pixel writes stay coherent with the GPU scan-out.
    g_fb_phys = fb_phys;
    g_fb_size = fb_size;
    init_graphics(fb, mbox[5], mbox[6], pitch);
    fb_ready = 1;
    return 1;
}

// ---------------------------------------------------------------------------
// Kernel entry
// ---------------------------------------------------------------------------

void kernel_main(void) {
    uart_init();
    uart_puts("\n[BOOT] RPi4 bare metal kernel started\n");

    // Bring the framebuffer up BEFORE enabling the MMU. With caches off the
    // framebuffer is naturally coherent with the GPU, and - crucially - this
    // gives us a screen to print on even if the MMU/cache bring-up is itself what
    // hangs on real silicon. boot_msg() mirrors progress to this screen once up,
    // so the last line you see is exactly where the kernel stopped.
    uart_puts("[FB] setting up framebuffer...\n");
    if (!setup_fb()) {
        uart_puts("[FB] ERROR: framebuffer setup failed\n");
    } else {
        cleardevice();
        boot_msg("[FB] framebuffer OK\n");
    }

    // Enable MMU + caches (big speed-up; also lets unaligned access work). On
    // real hardware this invalidates stale firmware cache state first.
    boot_msg("[MMU] enabling MMU + caches...\n");
    mmu_init();
    mmu_set_noncached(g_fb_phys, g_fb_size);   // re-mark FB NC (mmu_init rebuilt the tables)
    boot_msg("[MMU] enabled\n");

    // Show the BerryBasic boot logo (con_splash draws it when the REPL banner
    // prints; clearing the boot-progress text first).
    int real_hw = board_real_hw();
    g_show_logo = 1;

    // Mount the SD card (the data partition holds the user's BASIC programs).
    boot_msg("[SD] mounting filesystem...\n");
    g_sd_ready = (stg_init() == 0);
    boot_msg(g_sd_ready ? "[SD] mounted\n" : "[SD] mount FAILED\n");

    // USB keyboard on the DWC2 OTG / USB-C port (this is what QEMU emulates).
    // NOTE: on a board whose only USB-C port is power, no device is present here;
    // if boot visibly stops on the next line, the DWC2 probe is the culprit.
    boot_msg("[USB] initialising keyboard (DWC2/USB-C)...\n");
    g_kbd_ok = usb_kbd_init();
    boot_msg(g_kbd_ok ? "[USB] keyboard ready\n"
                      : "[USB] no USB-C keyboard\n");

    // On real hardware the USB-A ports are behind the VL805 xHCI on PCIe; bring
    // it up and look for a keyboard there too. QEMU does not model the PCIe
    // controller (touching it faults), so only do this on real hardware.
    if (!g_kbd_ok && real_hw) {
        boot_msg("[USB] trying USB-A (PCIe/VL805 xHCI)...\n");
        uintptr_t xhci_mmio = pcie_init();
        if (xhci_mmio) g_xhci_ok = xhci_kbd_init(xhci_mmio);
        boot_msg(g_xhci_ok ? "[USB] USB-A keyboard ready\n"
                           : "[USB] no USB-A keyboard\n");
    }

    // Write the full boot log to BOOTLOG.TXT on the data partition so USB
    // enumeration can be diagnosed on real hardware (no serial cable needed).
    flush_boot_log();

    // Hand control to the BASIC interpreter (runs forever on the target).
    boot_msg("[LOOP] entering BASIC\n");
    basic_init();
    basic_repl();
}
